'use strict';
(() => {
  if(!location.hostname.endsWith('github.io')) return;
  const ENDPOINT='https://graphql.anilist.co';
  const nativeFetch=window.fetch.bind(window);
  const pending=new Map();
  const PAGE_TTL=10*60*1000;
  const fields=`id title{romaji english native userPreferred} coverImage{extraLarge large color} format status genres tags{name rank} startDate{year month day} relations{edges{relationType}}`;
  const query=`query($page:Int,$year:Int,$season:MediaSeason){Page(page:$page,perPage:50){pageInfo{hasNextPage total}media(type:ANIME,isAdult:false,seasonYear:$year,season:$season,sort:[START_DATE_DESC]){${fields}}}}`;
  const seasons={inverno:'WINTER',primavera:'SPRING',verao:'SUMMER',outono:'FALL'};
  function currentSeason(){const now=new Date(),month=Number(new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',month:'numeric'}).format(now)),year=Number(new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',year:'numeric'}).format(now));return{year,season:month<=3?'WINTER':month<=6?'SPRING':month<=9?'SUMMER':'FALL'}}
  function selection(){let p=location.pathname.replace(/^\/AniNexus/,'')||'/';const m=p.match(/^\/animes\/temporadas\/(\d{4})\/(inverno|primavera|verao|outono)\/?$/);if(m)return{year:Number(m[1]),season:seasons[m[2]],onPage:true};if(/^\/animes\/temporadas\/?$/.test(p))return{...currentSeason(),onPage:true};return{...currentSeason(),onPage:false}}
  const sel=selection();
  const key=(page,year=sel.year,season=sel.season)=>`nx:v9:gql:${year}:${season}:${page}`;
  const seasonKey=(year=sel.year,season=sel.season)=>`nx:v8:season:${year}:${season}`;
  const read=k=>{try{const x=JSON.parse(sessionStorage.getItem(k)||'null');return x&&Date.now()-x.t<PAGE_TTL&&typeof x.text==='string'?x.text:null}catch{return null}};
  const write=(k,text)=>{try{sessionStorage.setItem(k,JSON.stringify({t:Date.now(),text}))}catch{}};
  const writeSeason=(pages,complete=false)=>{try{if(!pages?.length)return;const items=[...new Map(pages.flatMap(j=>j?.data?.Page?.media||[]).filter(x=>x?.id).map(x=>[x.id,x])).values()];const data={items,apiTotal:Number(pages[0]?.data?.Page?.pageInfo?.total||items.length),partial:!complete,hash:items.map(x=>`${x.id}:${x.status||''}`).join('|')};localStorage.setItem(seasonKey(),JSON.stringify({savedAt:Date.now(),data}))}catch{}};
  function fetchPage(page,year=sel.year,season=sel.season){const k=key(page,year,season),cached=read(k);if(cached)return Promise.resolve(cached);if(pending.has(k))return pending.get(k);const p=nativeFetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({query,variables:{page,year,season}})}).then(async r=>{const text=await r.text();if(!r.ok)throw new Error('HTTP '+r.status);write(k,text);return text}).finally(()=>pending.delete(k));pending.set(k,p);return p}
  window.fetch=async function(input,init){try{const url=typeof input==='string'?input:input?.url;if(url===ENDPOINT&&String(init?.method||'GET').toUpperCase()==='POST'&&typeof init?.body==='string'){const body=JSON.parse(init.body),v=body?.variables||{},q=String(body?.query||'');if(Number.isInteger(Number(v.page))&&Number.isInteger(Number(v.year))&&v.season&&q.includes('seasonYear:$year')&&q.includes('relations{edges{relationType}}')){if(init?.signal?.aborted)throw new DOMException('Aborted','AbortError');const text=await fetchPage(Number(v.page),Number(v.year),String(v.season));if(init?.signal?.aborted)throw new DOMException('Aborted','AbortError');return new Response(text,{status:200,headers:{'content-type':'application/json','x-aninexus-cache':'prefetch'}})}}}catch(err){if(err?.name==='AbortError')throw err}return nativeFetch(input,init)};
  const saveData=navigator.connection?.saveData||/2g/.test(navigator.connection?.effectiveType||'');const parse=text=>{try{return text?JSON.parse(text):null}catch{return null}};let warming=null;
  async function warm(){if(warming)return warming;warming=(async()=>{const pages=[];const first=parse(await fetchPage(1));if(!first)return pages;pages.push(first);writeSeason(pages,!first?.data?.Page?.pageInfo?.hasNextPage);if(saveData||!first?.data?.Page?.pageInfo?.hasNextPage)return pages;for(let page=2;page<=5;page++){if(page>2)await new Promise(r=>setTimeout(r,40));const json=parse(await fetchPage(page).catch(()=>null));if(!json)break;pages.push(json);const complete=!json?.data?.Page?.pageInfo?.hasNextPage;writeSeason(pages,complete);if(complete)break}return pages})().catch(()=>[]);return warming}
  if(sel.onPage){warm()}else{const idle=()=>fetchPage(1).then(t=>{const j=parse(t);if(j)writeSeason([j],!j?.data?.Page?.pageInfo?.hasNextPage)}).catch(()=>{});if(!saveData){('requestIdleCallback'in window?requestIdleCallback(idle,{timeout:1600}):setTimeout(idle,1000))}let intent=false;const onIntent=e=>{if(intent)return;const a=e.target?.closest?.('a[href*="/animes/temporadas"]');if(!a)return;intent=true;warm()};document.addEventListener('pointerover',onIntent,{passive:true,capture:true});document.addEventListener('pointerdown',onIntent,{passive:true,capture:true})}
})();
