function injectIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>{const i=ICON[el.dataset.icon];if(i)el.innerHTML=i})}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function strip(s=''){const d=document.createElement('div');d.innerHTML=s||'';return d.textContent||''}
function titleOf(m){return m?.title||m?.titleEnglish||m?.title?.english||m?.title?.userPreferred||m?.title?.romaji||m?.titleRomaji||'Anime'}
function formatName(f){return FORMAT_PT[f]||f||'Anime'}function genreName(g){return GENRE_PT[g]||g}
function scoreValue(m){const n=m?.score??(m?.averageScore?m.averageScore/10:null);return n?Number(n).toFixed(1).replace('.0',''):''}
function imageOf(m){return m?.cover||m?.coverImage?.extraLarge||m?.coverImage?.large||''}
function bannerOf(m){return m?.banner||m?.bannerImage||imageOf(m)}
function slugify(s){return String(s||'titulo').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90)}
function mediaPath(m,type='anime'){return `/${type}/${slugify(titleOf(m))}-${m.id}`}
function saveFavorites(){localStorage.setItem('aninexus:favorites',JSON.stringify([...state.favorites]))}
function saveAlerts(){localStorage.setItem('aninexus:alerts',JSON.stringify([...state.alerts]))}
function saveList(){localStorage.setItem('aninexus:list',JSON.stringify([...state.list]))}
function toast(msg){const n=document.createElement('div');n.className='toast';n.textContent=msg;document.querySelector('#toastStack').append(n);setTimeout(()=>n.remove(),2800)}
function routePath(){let p=location.pathname;if(IS_PAGES)p=p.replace(/^\/AniNexus/,'')||'/';return p.replace(/\/+$/,'')||'/'}
function go(path,replace=false){const url=BASE+(path==='/'?'/':path);history[replace?'replaceState':'pushState']({},'',url);closeDrawer();closeSearch();render()}
function restorePagesRoute(){if(!IS_PAGES)return;const u=new URL(location.href),p=u.searchParams.get('p');if(p){u.searchParams.delete('p');history.replaceState({},'',BASE+(p.startsWith('/')?p:'/'+p));}}
function setMeta(title){document.title=`${title} | AniNexus`}
function setTheme(t){state.theme=t;localStorage.setItem('aninexus:theme',t);document.documentElement.dataset.theme=t;const b=document.querySelector('[data-action="theme"]');if(b)b.innerHTML=ICON[t==='dark'?'moon':'sun']}
function openDrawer(){const d=document.querySelector('#drawer');d.hidden=false;d.setAttribute('aria-hidden','false');document.body.classList.add('drawer-open')}
function closeDrawer(){const d=document.querySelector('#drawer');if(!d)return;d.hidden=true;d.setAttribute('aria-hidden','true');document.body.classList.remove('drawer-open')}
function openSearch(){const l=document.querySelector('#searchLayer');l.hidden=false;l.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');setTimeout(()=>document.querySelector('#globalSearch')?.focus(),30)}
function closeSearch(){const l=document.querySelector('#searchLayer');if(!l)return;l.hidden=true;l.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
function openAuth(mode='login'){const l=document.querySelector('#authLayer');l.hidden=false;l.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');const c=document.querySelector('#authContent');if(IS_PAGES){c.innerHTML=`<h2>${mode==='login'?'Entrar':'Criar conta'}</h2><p>A interface de contas já está preparada. Login, sessões e banco entram em funcionamento quando o AniNexus for publicado no servidor.</p><button class="btn btn--primary" style="width:100%;margin-top:12px" data-action="auth-close">Entendi</button>`}else{c.innerHTML=`<h2>${mode==='login'?'Entrar':'Criar conta'}</h2><p>${mode==='login'?'Continue de onde parou.':'Crie sua lista e registre o que você assiste.'}</p><form id="authForm"><div class="field">${mode==='register'?'<label>Usuário</label><input name="username" required minlength="3" autocomplete="username">':''}<label>${mode==='login'?'E-mail ou usuário':'E-mail'}</label><input name="login" type="${mode==='login'?'text':'email'}" required autocomplete="email"><label>Senha</label><input name="password" type="password" required minlength="10" autocomplete="current-password"></div><button class="btn btn--primary" style="width:100%">${mode==='login'?'Entrar':'Criar conta'}</button></form>`;wireAuthForm(mode)}injectIcons(c)}
function closeAuth(){const l=document.querySelector('#authLayer');l.hidden=true;l.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
function wireAuthForm(mode){const f=document.querySelector('#authForm');if(!f)return;f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),body=mode==='login'?{login:fd.get('login'),password:fd.get('password')}:{username:fd.get('username'),email:fd.get('login'),password:fd.get('password')};try{await fetch(`/api/auth/${mode==='login'?'login':'register'}`,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(async r=>{if(!r.ok)throw Error((await r.json().catch(()=>({}))).error||'Falha')});toast(mode==='login'?'Login realizado':'Conta criada');closeAuth()}catch{toast('Não foi possível concluir agora')}}}

async function gql(query,variables={}){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),12000);try{const r=await fetch(GQL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query,variables}),signal:ctl.signal});if(!r.ok)throw Error('HTTP '+r.status);const j=await r.json();if(j.errors?.length)throw Error(j.errors[0].message);return j.data}finally{clearTimeout(timer)}}
function normalize(m){if(!m)return null;return{id:m.id,title:m.title?.english||m.title?.userPreferred||m.title?.romaji||m.title?.native||'Título',titleRomaji:m.title?.romaji||'',titleNative:m.title?.native||'',cover:m.coverImage?.extraLarge||m.coverImage?.large||'',banner:m.bannerImage||'',description:strip(m.description||''),genres:m.genres||[],tags:(m.tags||[]).slice(0,12).map(t=>t.name),score:m.averageScore?m.averageScore/10:null,popularity:m.popularity||0,favourites:m.favourites||0,episodes:m.episodes||null,chapters:m.chapters||null,volumes:m.volumes||null,duration:m.duration||null,format:m.format||'',status:m.status||'',season:m.season||'',seasonYear:m.seasonYear||null,country:m.countryOfOrigin||'',source:m.source||'',startDate:m.startDate||null,endDate:m.endDate||null,studios:(m.studios?.nodes||[]).map(s=>({id:s.id,name:s.name})),nextAiringEpisode:m.nextAiringEpisode||null,trailer:m.trailer||null,streaming:(m.externalLinks||[]).filter(x=>String(x.type||'').toUpperCase()==='STREAMING').map(x=>({site:x.site,url:x.url,icon:x.icon,color:x.color})),externalLinks:m.externalLinks||[]}}
const FIELDS=`id title{romaji english native userPreferred} coverImage{extraLarge large color} bannerImage description genres tags{name rank} averageScore popularity favourites episodes duration format status season seasonYear countryOfOrigin source startDate{year month day} endDate{year month day} studios(isMain:true){nodes{id name}} nextAiringEpisode{airingAt episode timeUntilAiring} trailer{id site thumbnail} externalLinks{site url type icon color}`;
