const MANGA_FIELDS=`id title{romaji english native userPreferred} coverImage{extraLarge large color} bannerImage description genres tags{name rank} averageScore popularity favourites chapters volumes format status countryOfOrigin source startDate{year month day} endDate{year month day} externalLinks{site url type icon color}`;
async function getCatalog(opts={}){if(!IS_PAGES){try{const q=new URLSearchParams();Object.entries(opts).forEach(([k,v])=>v!=null&&v!==''&&q.set(k,v));return await fetch('/api/catalog?'+q,{credentials:'same-origin'}).then(r=>{if(!r.ok)throw Error();return r.json()})}catch{}}
 const sortMap={POPULAR:['POPULARITY_DESC'],SCORE:['SCORE_DESC'],TRENDING:['TRENDING_DESC'],NEW:['START_DATE_DESC'],TITLE:['TITLE_ROMAJI']};const query=`query($page:Int,$perPage:Int,$search:String,$genre:String,$format:MediaFormat,$season:MediaSeason,$year:Int,$sort:[MediaSort]){Page(page:$page,perPage:$perPage){pageInfo{total currentPage lastPage hasNextPage}media(type:ANIME,isAdult:false,search:$search,genre:$genre,format:$format,season:$season,seasonYear:$year,sort:$sort){${FIELDS}}}}`;const d=await gql(query,{page:+(opts.page||1),perPage:+(opts.perPage||24),search:opts.search||null,genre:opts.genre||null,format:opts.format||null,season:opts.season||null,year:opts.year?+opts.year:null,sort:sortMap[opts.sort]||['POPULARITY_DESC']});return{pageInfo:d.Page.pageInfo,items:d.Page.media.map(normalize)}}
async function getReading(opts={}){if(!IS_PAGES){try{const q=new URLSearchParams();Object.entries(opts).forEach(([k,v])=>v!=null&&v!==''&&q.set(k,v));const r=await fetch('/api/reading?'+q,{credentials:'same-origin'});if(r.ok)return await r.json()}catch{}}
 const query=`query($page:Int,$perPage:Int,$search:String,$format:MediaFormat,$sort:[MediaSort]){Page(page:$page,perPage:$perPage){pageInfo{total currentPage lastPage hasNextPage}media(type:MANGA,isAdult:false,search:$search,format:$format,sort:$sort){${MANGA_FIELDS}}}}`;const d=await gql(query,{page:+(opts.page||1),perPage:+(opts.perPage||24),search:opts.search||null,format:opts.format||'MANGA',sort:['POPULARITY_DESC']});return{pageInfo:d.Page.pageInfo,items:d.Page.media.map(normalize)}}
function scheduleWindow(){const now=new Date();const todayKey=dateKey(now);const start=new Date(todayKey+'T00:00:00-03:00');return{start,end:new Date(start.getTime()+7*864e5),startUnix:Math.floor(start/1000),endUnix:Math.floor((start.getTime()+7*864e5)/1000)}}
async function getSchedule(){const w=scheduleWindow();if(!IS_PAGES){try{return await fetch(`/api/schedule?start=${w.startUnix}&end=${w.endUnix}`,{credentials:'same-origin'}).then(r=>{if(!r.ok)throw Error();return r.json()})}catch{}}
 const query=`query($page:Int,$start:Int,$end:Int){Page(page:$page,perPage:50){pageInfo{hasNextPage}airingSchedules(airingAt_greater:$start,airingAt_lesser:$end,sort:TIME){airingAt episode media{${FIELDS}}}}}`;let page=1,out=[];while(page<=5){const d=await gql(query,{page,start:w.startUnix,end:w.endUnix});out.push(...d.Page.airingSchedules.map(a=>({airingAt:a.airingAt,episode:a.episode,media:normalize(a.media)})));if(!d.Page.pageInfo.hasNextPage)break;page++}return out}
async function getMedia(id,type='ANIME'){if(type==='ANIME'&&!IS_PAGES){try{return await fetch('/api/anime/'+id,{credentials:'same-origin'}).then(r=>{if(!r.ok)throw Error();return r.json()})}catch{}}
 const fields=type==='ANIME'?FIELDS:MANGA_FIELDS;const extras=type==='ANIME'?`characters(perPage:12,sort:[ROLE,RELEVANCE,ID]){edges{role node{id name{full native} image{large medium}}}} staff(perPage:12,sort:[RELEVANCE,ID]){edges{role node{id name{full native} image{large medium}}}} relations{edges{relationType node{${FIELDS}}}} recommendations(perPage:8,sort:RATING_DESC){nodes{rating mediaRecommendation{${FIELDS}}}}`:`relations{edges{relationType node{${MANGA_FIELDS}}}} recommendations(perPage:8,sort:RATING_DESC){nodes{rating mediaRecommendation{${MANGA_FIELDS}}}}`;
 const d=await gql(`query($id:Int){Media(id:$id,type:${type}){${fields} ${extras}}}`,{id:+id}),m=d.Media,b=normalize(m);return{...b,characters:(m.characters?.edges||[]).map(e=>({role:e.role,id:e.node.id,name:e.node.name?.full||'',native:e.node.name?.native||'',image:e.node.image?.large||e.node.image?.medium||''})),staff:(m.staff?.edges||[]).map(e=>({role:e.role,id:e.node.id,name:e.node.name?.full||'',image:e.node.image?.large||e.node.image?.medium||''})),relations:(m.relations?.edges||[]).map(e=>({relationType:e.relationType,media:normalize(e.node)})),recommendations:(m.recommendations?.nodes||[]).map(n=>({rating:n.rating,media:normalize(n.mediaRecommendation)})).filter(x=>x.media)}}
async function searchMedia(text,type='ANIME'){if(!text)return[];if(type==='ANIME'&&!IS_PAGES){try{return (await getCatalog({search:text,perPage:8,page:1})).items}catch{}}
 const fields=type==='ANIME'?FIELDS:MANGA_FIELDS;const d=await gql(`query($search:String){Page(page:1,perPage:8){media(type:${type},isAdult:false,search:$search,sort:POPULARITY_DESC){${fields}}}}`,{search:text});return d.Page.media.map(normalize)}

function dateKey(d){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function nextDays(){const w=scheduleWindow();return Array.from({length:7},(_,i)=>{const d=new Date(w.start.getTime()+i*864e5);return{date:d,key:dateKey(d),dow:DOW[d.getDay()],full:DOW_FULL[d.getDay()],day:new Intl.DateTimeFormat('pt-BR',{timeZone:TZ,day:'2-digit'}).format(d)}})}
function fmtTime(ts){return new Intl.DateTimeFormat('pt-BR',{timeZone:TZ,hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(ts*1000))}
function countdownMarkup(ts){if(!ts||ts*1000<=Date.now())return'';return `<div class="countdown-wrap"><small>FALTAM</small><div class="air-countdown" data-countdown="${ts}"><span><b data-unit="d">00</b><em>d</em></span><i>:</i><span><b data-unit="h">00</b><em>h</em></span><i>:</i><span><b data-unit="m">00</b><em>m</em></span><i>:</i><span><b data-unit="s">00</b><em>s</em></span></div></div>`}
function tickCountdowns(){document.querySelectorAll('[data-countdown]').forEach(el=>{let sec=Math.max(0,Math.floor(+el.dataset.countdown-Date.now()/1000)),d=Math.floor(sec/86400);sec%=86400;let h=Math.floor(sec/3600);sec%=3600;let m=Math.floor(sec/60),ss=sec%60;for(const [k,v] of Object.entries({d,h,m,s:ss})){const n=el.querySelector(`[data-unit="${k}"]`);if(n)n.textContent=String(v).padStart(2,'0')}el.classList.toggle('with-days',d>0)})}
function startCountdowns(){if(state.countdownTimer)clearInterval(state.countdownTimer);tickCountdowns();state.countdownTimer=setInterval(tickCountdowns,1000)}
function fmtDateObj(d){if(!d?.year)return'—';return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(d.year,(d.month||1)-1,d.day||1))).replace('.','')}
function currentSeason(){const d=new Date(),m=+new Intl.DateTimeFormat('en',{timeZone:TZ,month:'numeric'}).format(d),y=+new Intl.DateTimeFormat('en',{timeZone:TZ,year:'numeric'}).format(d);return{season:m<=3?'WINTER':m<=6?'SPRING':m<=9?'SUMMER':'FALL',year:y}}
function seasonShift(s,y,n){const a=['WINTER','SPRING','SUMMER','FALL'];let i=a.indexOf(s)+n;while(i<0){i+=4;y--}while(i>3){i-=4;y++}return{season:a[i],year:y}}
function compactNumber(n){return new Intl.NumberFormat('pt-BR',{notation:'compact',maximumFractionDigits:1}).format(n||0)}
function statusName(s){return({FINISHED:'Finalizado',RELEASING:'Em andamento',NOT_YET_RELEASED:'Em breve',CANCELLED:'Cancelado',HIATUS:'Em hiato'})[s]||s||'—'}
function sourceName(s){return({MANGA:'Mangá',LIGHT_NOVEL:'Light novel',ORIGINAL:'Original',NOVEL:'Novel',GAME:'Jogo',VISUAL_NOVEL:'Visual novel',WEB_NOVEL:'Web novel'})[s]||s||'—'}
