'use strict';
(() => {
  const app=document.querySelector('#app');
  if(!app)return;
  const API='https://graphql.anilist.co';
  const IS_PAGES=location.hostname.endsWith('github.io');
  const BASE=IS_PAGES?'/AniNexus':'';
  const BUILD='24.0.0';
  let countdownTimer=null,topTimer=null,mounted=false;

  const I={
    arrow:'<svg viewBox="0 0 24 24"><path d="M5 12h13M14 7.5 18.5 12 14 16.5"/></svg>',
    back:'<svg viewBox="0 0 24 24"><path d="m15 5-7 7 7 7"/></svg>',
    star:'<svg viewBox="0 0 24 24"><path d="m12 3 2.8 5.5 6.1.9-4.4 4.3 1 6.1-5.5-2.9-5.5 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>',
    plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
    heart:'<svg viewBox="0 0 24 24"><path d="M20.7 8.7c0 5-8.7 10.1-8.7 10.1S3.3 13.7 3.3 8.7A4.6 4.6 0 0 1 12 6.2a4.6 4.6 0 0 1 8.7 2.5Z"/></svg>',
    trophy:'<svg viewBox="0 0 24 24"><path d="M8 4h8v4c0 4-1.7 7-4 7s-4-3-4-7V4Z"/><path d="M8 6H4v2c0 2.4 1.7 4 4.2 4M16 6h4v2c0 2.4-1.7 4-4.2 4M12 15v4M8 21h8"/></svg>',
    calendar:'<svg viewBox="0 0 24 24"><rect x="3" y="5.2" width="18" height="15.5" rx="2.3"/><path d="M7.6 3v4.2M16.4 3v4.2M3 9.3h18"/></svg>',
    discover:'<svg viewBox="0 0 24 24"><path d="m12 3 1.5 4.3L18 8.8l-4.5 1.5L12 14.7l-1.5-4.4L6 8.8l4.5-1.5L12 3Z"/><path d="m19 14 .8 2.2 2.2.8-2.2.8L19 20l-.8-2.2L16 17l2.2-.8L19 14Z"/></svg>',
    book:'<svg viewBox="0 0 24 24"><path d="M4 4.5c3.5-.8 6.2-.2 8 1.7v14c-1.8-1.9-4.5-2.5-8-1.7v-14Z"/><path d="M20 4.5c-3.5-.8-6.2-.2-8 1.7v14c1.8-1.9 4.5-2.5 8-1.7v-14Z"/></svg>',
    news:'<svg viewBox="0 0 24 24"><path d="M4 5.3h12.5v13.4H4z"/><path d="M7 8.2h6.5M7 11.3h6.5M7 14.4h4.5"/><path d="M16.5 8h3.5v10.7h-3.5"/></svg>',
    chat:'<svg viewBox="0 0 24 24"><path d="M4 5.5h16v11H9l-5 3v-14Z"/><path d="M8 9h8M8 12.5h5"/></svg>',
    play:'<svg viewBox="0 0 24 24"><path d="m9 6 9 6-9 6V6Z"/></svg>',
    fire:'<svg viewBox="0 0 24 24"><path d="M13 2c1 4-2 5-1 8 1.5-2 3-2.5 4-5 3 3 5 6 5 10a9 9 0 1 1-18 0c0-4 2-7 5-10 0 3 1 4 2 5 0-3 1-5 3-8Z"/></svg>'
  };
  const STATUS={PLANNING:'Quero Ver',CURRENT:'Assistindo',COMPLETED:'Terminei',PAUSED:'Pausei',DROPPED:'Desisti'};
  const GENRE={Action:'Ação',Adventure:'Aventura',Comedy:'Comédia',Drama:'Drama',Fantasy:'Fantasia',Horror:'Terror',Mystery:'Mistério',Romance:'Romance','Sci-Fi':'Ficção Científica','Slice of Life':'Slice of Life',Sports:'Esportes',Supernatural:'Sobrenatural',Thriller:'Suspense',Music:'Música',Psychological:'Psicológico',Mecha:'Mecha'};
  const AWARDS=[
    ['Anime do Ano','My Hero Academia FINAL SEASON','My Hero Academia Final Season'],
    ['Filme do Ano','Demon Slayer: Kimetsu no Yaiba Infinity Castle','Demon Slayer Infinity Castle'],
    ['Melhor Continuação','ONE PIECE','One Piece'],
    ['Melhor Série Estreante','Gachiakuta','Gachiakuta'],
    ['Melhor Anime Original','Lazarus','Lazarus'],
    ['Melhor Animação','Solo Leveling Season 2 -Arise from the Shadow-','Solo Leveling Season 2'],
    ['Melhor Romance','The Fragrant Flower Blooms With Dignity','The Fragrant Flower Blooms With Dignity']
  ];
  const FIELDS='id title{romaji english native userPreferred} coverImage{extraLarge large} bannerImage averageScore popularity favourites genres episodes format status seasonYear nextAiringEpisode{airingAt episode}';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const title=m=>m?.title?.english||m?.title?.userPreferred||m?.title?.romaji||m?.title?.native||'Anime';
  const image=m=>m?.coverImage?.extraLarge||m?.coverImage?.large||'';
  const banner=m=>m?.bannerImage||image(m);
  const score=m=>m?.averageScore?String((m.averageScore/10).toFixed(1)).replace('.0',''):'';
  const slug=s=>String(s||'anime').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90);
  const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k)||'null');return v??f}catch{return f}};
  const setOf=k=>new Set((read(k,[])||[]).map(Number));

  function route(){
    try{const u=new URL(location.href),p=u.searchParams.get('p');if(p)return p.split('?')[0].replace(/\/+$/,'')||'/';let x=u.pathname;if(IS_PAGES)x=x.replace(/^\/AniNexus/,'')||'/';return x.replace(/\/+$/,'')||'/'}catch{return'/'}
  }
  function homeWanted(){return !!window.__NX_HOME_V24_BOOT__||route()==='/'||route()==='/__nx_home_v24_boot__'}
  function restore(){if(!window.__NX_HOME_V24_BOOT__)return;history.replaceState({},'',IS_PAGES?`${BASE}/?build=${BUILD}&p=%2F`:'/');delete window.__NX_HOME_V24_BOOT__;document.documentElement.classList.remove('nx24-home-boot')}
  async function gql(query,variables={}){let last;for(let i=0;i<3;i++){try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({query,variables})});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();if(j.errors?.length)throw new Error(j.errors[0]?.message||'API');return j.data}catch(e){last=e;if(i<2)await new Promise(r=>setTimeout(r,350*(i+1)))} }throw last}
  function seasonNow(){const d=new Date(),m=Number(new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',month:'numeric'}).format(d)),year=Number(new Intl.DateTimeFormat('en',{timeZone:'America/Sao_Paulo',year:'numeric'}).format(d));return{year,season:m<=3?'WINTER':m<=6?'SPRING':m<=9?'SUMMER':'FALL',label:m<=3?'Inverno':m<=6?'Primavera':m<=9?'Verão':'Outono'}}
  async function pageQuery(args={}){const vars={page:1,per:args.per||12},defs=['$page:Int','$per:Int'],call=['type:ANIME','isAdult:false'];if(args.season){defs.push('$season:MediaSeason','$year:Int');vars.season=args.season;vars.year=args.year;call.push('season:$season','seasonYear:$year')}if(args.status){defs.push('$status:MediaStatus');vars.status=args.status;call.push('status:$status')}const sort=args.sort||'POPULARITY_DESC';const q=`query(${defs.join(',')}){Page(page:$page,perPage:$per){media(${call.join(',')},sort:[${sort}]){${FIELDS}}}}`;return(await gql(q,vars))?.Page?.media||[]}
  async function scheduleQuery(){const now=Math.floor(Date.now()/1000);const q=`query($now:Int){Page(page:1,perPage:12){airingSchedules(airingAt_greater:$now,sort:TIME){airingAt episode media{${FIELDS}}}}}`;return(await gql(q,{now}))?.Page?.airingSchedules||[]}
  async function readingQuery(){const q=`query{Page(page:1,perPage:12){media(type:MANGA,isAdult:false,sort:[POPULARITY_DESC]){id title{romaji english native userPreferred} coverImage{extraLarge large} averageScore genres format}}}`;return(await gql(q))?.Page?.media||[]}
  async function byIds(ids){if(!ids.length)return[];const q=`query($ids:[Int]){Page(page:1,perPage:20){media(id_in:$ids,type:ANIME,isAdult:false){${FIELDS}}}}`;return(await gql(q,{ids:ids.slice(0,20)}))?.Page?.media||[]}
  async function awardQuery(){const fields=`id title{romaji english native userPreferred} coverImage{extraLarge large} averageScore genres`;const aliases=AWARDS.map((x,i)=>`a${i}:Media(search:${JSON.stringify(x[2])},type:ANIME){${fields}}`).join(' ');const d=await gql(`query{${aliases}}`);return AWARDS.map((a,i)=>({...{category:a[0],display:a[1]},media:d?.[`a${i}`]})).filter(x=>x.media)}

  function card(m,type='anime'){const st=window.AniNexusMediaState?.get?.(m.id)?.status||'';const fav=setOf('aninexus:favorites').has(Number(m.id));return `<article class="nx24-card" data-nx24-open="${m.id}" data-kind="${type}" data-nx-media="${m.id}"><div class="nx24-card-poster">${image(m)?`<img loading="lazy" decoding="async" src="${esc(image(m))}" alt="${esc(title(m))}">`:''}<div class="nx24-card-shade"></div>${score(m)?`<span class="nx24-score">${I.star}${score(m)}</span>`:''}${type==='anime'?`<div class="nx24-card-actions"><button type="button" data-list="${m.id}" class="${st?'active':''}" aria-label="Adicionar à lista">${I.plus}</button><button type="button" data-fav="${m.id}" class="${fav?'active':''}" aria-label="Favoritar">${I.heart}</button></div>`:''}</div><h3>${esc(title(m))}</h3><p>${esc((m.genres||[]).slice(0,2).map(g=>GENRE[g]||g).join(' · '))}</p></article>`}
  function rail(id,html){return `<div class="nx24-rail-wrap"><button class="nx24-rail-btn prev" data-nx24-rail="${id}" data-dir="-1" aria-label="Anterior">${I.back}</button><div class="nx24-rail" id="${id}">${html}</div><button class="nx24-rail-btn next" data-nx24-rail="${id}" data-dir="1" aria-label="Próximo">${I.arrow}</button></div>`}
  function sectionHead(t,s,href,label='Ver mais'){return `<div class="nx24-section-head"><div><h2>${t}</h2><p>${s||''}</p></div>${href?`<a href="${href}" data-link>${label}${I.arrow}</a>`:''}</div>`}
  function skeleton(n=8){return Array.from({length:n},()=>'<div class="nx24-loading" style="height:255px"></div>').join('')}
  function countdown(ts){const d=ts*1000-Date.now();if(d<=0)return'Em instantes';const days=Math.floor(d/86400000),h=Math.floor(d%86400000/3600000),m=Math.floor(d%3600000/60000),s=Math.floor(d%60000/1000);return days?`${days}d ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
  function relative(ts){if(!ts)return'';const d=Date.now()-ts;if(d<60000)return'agora';if(d<3600000)return`${Math.floor(d/60000)}min`;if(d<86400000)return`${Math.floor(d/3600000)}h`;return`${Math.floor(d/86400000)}d`}

  function personalSnapshot(){const states=read('aninexus:mediaState:v2',{}),favorites=setOf('aninexus:favorites');const entries=Object.entries(states).map(([id,s])=>({id:Number(id),...s})).filter(x=>x.status).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));return{states,entries,favorites,completed:entries.filter(x=>x.status==='COMPLETED').length,current:entries.filter(x=>x.status==='CURRENT').length,paused:entries.filter(x=>x.status==='PAUSED').length,planning:entries.filter(x=>x.status==='PLANNING').length,scored:entries.filter(x=>x.score!=null).length}}
  function achievements(p){const total=p.entries.length,f=p.favorites.size;const rows=[['Primeiro passo','Adicione seu primeiro anime',total,1,I.discover],['Maratonista','Conclua 5 animes',p.completed,5,I.play],['Colecionador','Favorite 10 títulos',f,10,I.heart],['Crítico Nato','Dê nota a 5 animes',p.scored,5,I.star]];return rows.map(([name,desc,val,max,icon])=>`<div class="nx24-achievement ${val>=max?'unlocked':''}"><i>${icon}</i><div><strong>${name}</strong><span>${desc} · ${Math.min(val,max)}/${max}</span><div class="nx24-progress"><b style="width:${Math.min(100,val/max*100)}%"></b></div></div></div>`).join('')}

  function shell(){const s=seasonNow(),p=personalSnapshot();app.innerHTML=`<div class="nx24-home" data-nx24-home>
    <section class="nx24-hero"><div class="nx24-shell nx24-hero-inner"><div class="nx24-hero-copy"><div class="nx24-kicker"><i class="nx24-icon">${I.discover}</i>de fã para fã</div><h1>Seu universo anime,<br><em>em um lugar só.</em></h1><p>Descubra o que assistir, acompanhe episódios, organize sua lista, explore mangás e participe de uma comunidade feita para quem realmente gosta de anime.</p><div class="nx24-hero-actions"><a class="primary" href="/animes/temporadas" data-link>Explorar ${s.label} ${s.year}${I.arrow}</a><a href="/animes/programacao" data-link>${I.calendar} Programação de hoje</a></div><div class="nx24-hero-points"><span><i></i>Catálogo em português</span><span><i></i>Lista sincronizada</span><span><i></i>Programação em Brasília</span></div></div><div class="nx24-showcase"><div class="nx24-showcase-glow"></div><div class="nx24-poster one nx24-loading" data-hero-poster="0"></div><div class="nx24-poster two nx24-loading" data-hero-poster="1"></div><div class="nx24-poster three nx24-loading" data-hero-poster="2"></div><div class="nx24-showcase-logo"><img src="${BASE}/assets/logo.png" alt="AniNexus"></div></div></div></section>
    <section class="nx24-account-band"><div class="nx24-shell nx24-account-inner"><div class="nx24-account-title"><span class="nx24-live"></span><div><strong>${p.entries.length?'Sua atividade':'Comece sua jornada'}</strong><span>${p.entries.length?'ações recentes da sua conta':'o AniNexus se adapta ao que você acompanha'}</span></div></div><div class="nx24-activity-rail" id="nx24Activity"><div class="nx24-activity empty">${p.entries.length?'Carregando suas ações…':'Use o + nos animes para montar sua lista e desbloquear esta área.'}</div></div></div></section>
    <section class="nx24-section"><div class="nx24-shell">${sectionHead(`Animes da Temporada · ${s.label} ${s.year}`,'O que está movimentando a temporada agora.','/animes/temporadas','ver temporada completa')}<div id="nx24Season">${rail('nx24SeasonRail',skeleton(8))}</div></div></section>
    <section class="nx24-section soft"><div class="nx24-shell">${sectionHead('Próximos Episódios','Horários de Brasília, contagem regressiva e acesso direto à programação.','/animes/programacao','Programação')}<div class="nx24-schedule-grid" id="nx24Schedule">${Array.from({length:6},()=>'<div class="nx24-loading" style="height:146px"></div>').join('')}</div></div></section>
    <section class="nx24-section"><div class="nx24-shell">${sectionHead('Top 10 Animes','Um ranking para navegar, não só uma tabela.','/melhores-animes-para-assistir','ver ranking completo')}<div class="nx24-top-shell"><div class="nx24-top-track" id="nx24Top">${Array.from({length:10},()=>'<div class="nx24-loading" style="width:225px;height:315px"></div>').join('')}</div><div class="nx24-top-controls"><button data-top-dir="-1">${I.back}</button><button data-top-dir="1">${I.arrow}</button></div></div></div></section>
    <section class="nx24-section soft"><div class="nx24-shell"><div class="nx24-awards"><div class="nx24-awards-head"><div class="nx24-awards-title"><i class="nx24-awards-icon">${I.trophy}</i><div><small>Crunchyroll Anime Awards</small><h2>Vencedores de 2026</h2></div></div><a href="/anime-awards" data-link>todas as categorias ${I.arrow}</a></div><div class="nx24-awards-grid" id="nx24Awards">${Array.from({length:7},()=>'<div class="nx24-loading" style="min-height:235px"></div>').join('')}</div></div></div></section>
    <section class="nx24-section"><div class="nx24-shell">${sectionHead('Sua jornada no AniNexus','A Home muda conforme você usa o site.')}<div class="nx24-user-grid"><div class="nx24-user-card"><h3>Conquistas</h3><p>Marcos desbloqueados pelas suas ações reais no AniNexus.</p><div class="nx24-achievements">${achievements(p)}</div></div><div class="nx24-user-card"><h3>Seu painel</h3><p>Um resumo rápido do que você está acompanhando.</p><div class="nx24-stats"><div class="nx24-stat"><strong>${p.current}</strong><span>assistindo</span></div><div class="nx24-stat"><strong>${p.completed}</strong><span>terminados</span></div><div class="nx24-stat"><strong>${p.planning}</strong><span>quero ver</span></div><div class="nx24-stat"><strong>${p.favorites.size}</strong><span>favoritos</span></div></div><div id="nx24Continue" style="margin-top:15px"></div></div></div></div></section>
    <section class="nx24-section soft"><div class="nx24-shell">${sectionHead('Animes mais Populares','Títulos que concentram mais atenção agora.','/animes-mais-assistidos','ver mais')}<div id="nx24Popular">${rail('nx24PopularRail',skeleton(8))}</div></div></section>
    <section class="nx24-section"><div class="nx24-shell">${sectionHead('Chegando em Breve','Próximas estreias para colocar no radar.','/animes-mais-aguardados','ver todos')}<div id="nx24Soon">${rail('nx24SoonRail',skeleton(8))}</div></div></section>
    <section class="nx24-section soft"><div class="nx24-shell">${sectionHead('Mangás & Light Novels','Continue histórias, descubra originais e acompanhe outras mídias.','/mangas','explorar leitura')}<div id="nx24Reading">${rail('nx24ReadingRail',skeleton(8))}</div></div></section>
    <section class="nx24-section"><div class="nx24-shell">${sectionHead('Explore o AniNexus','Tudo conversa com a mesma lista, favoritos e conta.')}<div class="nx24-explore-grid"><a class="nx24-explore" href="/animes/catalogo" data-link><i>${I.discover}</i><div><strong>Catálogo</strong><span>Filtros, notas e descoberta</span></div></a><a class="nx24-explore" href="/animes/programacao" data-link><i>${I.calendar}</i><div><strong>Programação</strong><span>Próximos episódios</span></div></a><a class="nx24-explore" href="/noticias" data-link><i>${I.news}</i><div><strong>Notícias</strong><span>Novidades relevantes</span></div></a><a class="nx24-explore" href="/comunidade" data-link><i>${I.chat}</i><div><strong>Comunidade</strong><span>Impressões e discussões</span></div></a><a class="nx24-explore" href="/mangas" data-link><i>${I.book}</i><div><strong>Mangás</strong><span>Leitura e adaptações</span></div></a><a class="nx24-explore" href="/anime-awards" data-link><i>${I.trophy}</i><div><strong>Anime Awards</strong><span>Vencedores e categorias</span></div></a></div></div></section>
    <section class="nx24-section soft"><div class="nx24-shell">${sectionHead('Tags','Encontre algo pelo clima que você quer assistir.')}<div class="nx24-tags">${['Ação','Aventura','Comédia','Drama','Fantasia','Romance','Mistério','Esportes','Sobrenatural','Terror','Psicológico','Mecha','Música','Slice of Life','Isekai','Shounen'].map(x=>`<a href="/animes/catalogo" data-link>${x}</a>`).join('')}</div></div></section>
  </div>`;document.title='Início | AniNexus';document.body.classList.add('nx24-home-active');document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav==='home'))}

  function updateActivity(media,p){const map=new Map(media.map(m=>[Number(m.id),m]));const host=document.querySelector('#nx24Activity');if(!host)return;if(!p.entries.length)return;host.innerHTML=p.entries.slice(0,10).map(x=>{const m=map.get(x.id),name=m?title(m):`Anime #${x.id}`,verb={PLANNING:'adicionou para ver',CURRENT:'está assistindo',COMPLETED:'terminou',PAUSED:'pausou',DROPPED:'desistiu'}[x.status]||'atualizou';const extras=[x.progress?`ep. ${x.progress}`:'',x.score!=null?`nota ${String(x.score).replace('.0','')}`:'',x.reaction||''].filter(Boolean).join(' · ');return `<div class="nx24-activity"><b>${esc(name)}</b> · ${verb}${extras?` · ${esc(extras)}`:''}${x.updatedAt?` · ${relative(x.updatedAt)}`:''}</div>`}).join('')}
  function scheduleCard(x){const m=x.media;return `<article class="nx24-schedule-card" data-nx24-open="${m.id}" data-kind="anime" data-nx-media="${m.id}"><img loading="lazy" src="${esc(image(m))}" alt="${esc(title(m))}"><div class="nx24-schedule-copy"><div class="nx24-air"><span>${new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',weekday:'short'}).format(new Date(x.airingAt*1000)).replace('.','').toUpperCase()}</span><b>${new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'}).format(new Date(x.airingAt*1000))}</b></div><div class="nx24-countdown" data-countdown="${x.airingAt}">${countdown(x.airingAt)}</div><h3>${esc(title(m))}</h3><p>${esc((m.genres||[]).slice(0,3).map(g=>GENRE[g]||g).join(', '))}</p></div><div class="nx24-ep"><small>EP</small><strong>${x.episode}</strong></div></article>`}
  function topCards(items){return items.slice(0,10).map((m,i)=>`<article class="nx24-top-card rank${i+1}" style="--i:${i}" data-nx24-open="${m.id}" data-kind="anime" data-nx-media="${m.id}"><span class="nx24-rank-number">${i+1}</span><div class="nx24-top-poster"><img loading="lazy" src="${esc(image(m))}" alt="${esc(title(m))}"></div><div class="nx24-top-info"><small>${i+1}º lugar · ${score(m)||'—'}</small><strong>${esc(title(m))}</strong><span>${esc((m.genres||[]).slice(0,2).map(g=>GENRE[g]||g).join(' · '))}</span></div></article>`).join('')}
  function awardCards(rows){return rows.map((x,i)=>`<article class="nx24-award-card" data-nx24-open="${x.media.id}" data-kind="anime"><img loading="lazy" src="${esc(banner(x.media)||image(x.media))}" alt="${esc(x.display)}"><div class="nx24-award-copy"><small>${esc(x.category)}</small><strong>${esc(x.display)}</strong></div></article>`).join('')}

  function wire(){document.querySelectorAll('[data-nx24-rail]').forEach(b=>b.onclick=()=>{const el=document.getElementById(b.dataset.nx24Rail);el?.scrollBy({left:Number(b.dataset.dir)*Math.max(280,el.clientWidth*.75),behavior:'smooth'})});document.querySelectorAll('[data-top-dir]').forEach(b=>b.onclick=()=>document.querySelector('#nx24Top')?.scrollBy({left:Number(b.dataset.topDir)*470,behavior:'smooth'}));document.querySelectorAll('[data-nx24-open]').forEach(el=>el.onclick=e=>{if(e.target.closest('[data-list],[data-fav]'))return;const id=Number(el.dataset.nx24Open);if(!id)return;const path=`/anime/${slug(el.querySelector('h3,strong')?.textContent||'anime')}-${id}`;location.assign(IS_PAGES?`${BASE}/?build=${BUILD}&p=${encodeURIComponent(path)}`:path)});window.AniNexusMediaState?.sync?.()}
  function topMotion(){const cards=[...document.querySelectorAll('.nx24-top-card')];if(!cards.length)return;const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.12});cards.forEach(c=>io.observe(c));if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const track=document.querySelector('#nx24Top');if(!track)return;let paused=false;track.addEventListener('pointerdown',()=>paused=true,{passive:true});track.addEventListener('pointerup',()=>setTimeout(()=>paused=false,2500),{passive:true});topTimer=setInterval(()=>{if(paused||document.hidden||!mounted)return;const max=track.scrollWidth-track.clientWidth;if(max<40)return;const next=track.scrollLeft+245;track.scrollTo({left:next>=max-20?0:next,behavior:'smooth'})},4200)}
  function timers(){clearInterval(countdownTimer);countdownTimer=setInterval(()=>document.querySelectorAll('[data-countdown]').forEach(el=>el.textContent=countdown(Number(el.dataset.countdown))),1000)}
  function cleanup(){mounted=false;clearInterval(countdownTimer);clearInterval(topTimer);countdownTimer=topTimer=null;document.body.classList.remove('nx24-home-active')}

  async function mount(){if(mounted)return;mounted=true;restore();shell();const s=seasonNow(),p=personalSnapshot();const personalIds=p.entries.slice(0,12).map(x=>x.id);const jobs=await Promise.allSettled([pageQuery({per:14,season:s.season,year:s.year,sort:'POPULARITY_DESC'}),scheduleQuery(),pageQuery({per:10,sort:'SCORE_DESC'}),awardQuery(),pageQuery({per:14,sort:'POPULARITY_DESC'}),pageQuery({per:14,status:'NOT_YET_RELEASED',sort:'POPULARITY_DESC'}),readingQuery(),byIds(personalIds)]);if(!mounted)return;
    const [seasonR,scheduleR,topR,awardsR,popR,soonR,readR,personalR]=jobs;
    if(seasonR.status==='fulfilled'){const a=seasonR.value;document.querySelector('#nx24Season').innerHTML=rail('nx24SeasonRail',a.map(m=>card(m)).join(''));a.slice(0,3).forEach((m,i)=>{const h=document.querySelector(`[data-hero-poster="${i}"]`);if(h){h.classList.remove('nx24-loading');h.innerHTML=`<img src="${esc(image(m))}" alt="">`}})}
    if(scheduleR.status==='fulfilled')document.querySelector('#nx24Schedule').innerHTML=scheduleR.value.slice(0,6).map(scheduleCard).join('')||'<div class="nx24-empty">Nenhum episódio próximo encontrado.</div>';
    if(topR.status==='fulfilled')document.querySelector('#nx24Top').innerHTML=topCards(topR.value);
    if(awardsR.status==='fulfilled')document.querySelector('#nx24Awards').innerHTML=awardCards(awardsR.value);
    if(popR.status==='fulfilled')document.querySelector('#nx24Popular').innerHTML=rail('nx24PopularRail',popR.value.map(m=>card(m)).join(''));
    if(soonR.status==='fulfilled')document.querySelector('#nx24Soon').innerHTML=rail('nx24SoonRail',soonR.value.map(m=>card(m)).join(''));
    if(readR.status==='fulfilled')document.querySelector('#nx24Reading').innerHTML=rail('nx24ReadingRail',readR.value.map(m=>card(m,'manga')).join(''));
    if(personalR.status==='fulfilled'){
      updateActivity(personalR.value,p);
      const currentIds=new Set(p.entries.filter(x=>x.status==='CURRENT'||x.status==='PAUSED').map(x=>x.id));
      const continueItems=personalR.value.filter(m=>currentIds.has(Number(m.id))).slice(0,3);
      const continueCards=continueItems.map(m=>{
        const st=p.states[m.id]||{},progress=st.progress?` · ep. ${st.progress}`:'';
        return `<button type="button" data-nx24-open="${m.id}" data-kind="anime" style="width:100%;border:1px solid rgba(255,255,255,.07);border-radius:10px;background:#100b0f;color:#fff;padding:9px;display:grid;grid-template-columns:38px 1fr auto;gap:9px;align-items:center;text-align:left;cursor:pointer"><img src="${esc(image(m))}" style="width:38px;height:50px;object-fit:cover;border-radius:6px"><span style="min-width:0"><b style="display:block;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${esc(title(m))}</b><small style="color:#80747a">${STATUS[st.status]||st.status}${progress}</small></span>${I.arrow}</button>`;
      }).join('');
      document.querySelector('#nx24Continue').innerHTML=continueItems.length?`<div style="display:grid;gap:7px">${continueCards}</div>`:'<div class="nx24-empty" style="min-height:75px">Marque um anime como Assistindo para ele aparecer aqui.</div>';
    }
    wire();topMotion();timers()}

  addEventListener('DOMContentLoaded',()=>{if(homeWanted())mount()},{once:true});if(document.readyState!=='loading'&&homeWanted())mount();addEventListener('popstate',()=>{if(route()==='/'){cleanup();mount()}else cleanup()});
})();
