'use strict';
(() => {
  if(window.__ANINEXUS_MANGA_V42__)return;window.__ANINEXUS_MANGA_V42__=true;
  const app=document.querySelector('#app'),IS_PAGES=location.hostname.endsWith('github.io'),BASE=IS_PAGES?'/AniNexus':'';
  if(!app)return;
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const svg={star:'<svg viewBox="0 0 24 24"><path d="m12 3 2.8 5.5 6.1.9-4.4 4.3 1 6.1-5.5-2.9-5.5 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>',heart:'<svg viewBox="0 0 24 24"><path d="M20.5 8.8c0 5-8.5 10-8.5 10s-8.5-5-8.5-10A4.6 4.6 0 0 1 12 6.4a4.6 4.6 0 0 1 8.5 2.4Z"/></svg>',plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',check:'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 7"/></svg>'};
  const statusLabels={PLANNING:'Quero ler',CURRENT:'Lendo',COMPLETED:'Terminei',PAUSED:'Pausei',DROPPED:'Desisti'};
  const state={items:new Map(),library:null};
  const mediaState=()=>window.AniNexusMangaState;
  const actionState={get list(){return new Map(Object.entries(mediaState()?.entries()||{}).map(([id,value])=>[Number(id),value]))},get favorites(){return mediaState()?.favorites()||new Set()}};
  function route(){const url=new URL(location.href),restored=url.searchParams.get('p');if(restored)return restored.split('?')[0].replace(/\/+$/,'')||'/';let path=url.pathname;if(IS_PAGES)path=path.replace(/^\/AniNexus/,'')||'/';return path.replace(/\/+$/,'')||'/'}
  function go(path){if(IS_PAGES)location.assign(`${BASE}/?build=44.23.0&p=${encodeURIComponent(path)}`);else if(!window.AniNexusGo?.(path))location.assign(path)}
  function slug(value){return String(value||'manga').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90)}
  function title(item){return item?.title?.english||item?.title?.userPreferred||item?.title?.romaji||item?.title||'Mangá'}
  function cover(item){return item?.coverImage?.extraLarge||item?.coverImage?.large||item?.cover||''}
  function score(item){if(item?.metricsSource!=='aninexus')return'';const value=item?.averageScore?Number(item.averageScore)/10:Number(item?.score);return Number.isFinite(value)&&value>0?value.toFixed(1).replace('.0',''):''}
  function formatLabel(value){return({MANGA:'Mangá',NOVEL:'Light novel',ONE_SHOT:'One-shot'})[value]||'Mangá'}
  function normalized(item){if(item?.coverImage)return item;const internal=item?.metricsSource==='aninexus';return{...item,title:{english:item.title,userPreferred:item.title,romaji:item.titleRomaji},coverImage:{extraLarge:item.cover,large:item.cover},averageScore:internal&&item.score?Number(item.score)*10:null,score:internal?item.score:null,meanScore:internal?item.meanScore:null,popularity:internal?Number(item.popularity||0):0,favourites:internal?Number(item.favourites||0):0,ratingCount:internal?Number(item.ratingCount||0):0,listCount:internal?Number(item.listCount||0):0}}
  async function api(path,options={}){if(path.startsWith('/api/me/')){if(!window.AniNexusAuth?.enabled)throw Object.assign(new Error('AUTH_REQUIRED'),{status:401});return window.AniNexusAuth.api(path,options)}const response=await fetch(path,{...options,headers:{accept:'application/json',...(options.headers||{})}});if(!response.ok)throw Object.assign(new Error(`HTTP ${response.status}`),{status:response.status});return response.json()}
  function syncMangaActions(){mediaState()?.sync()}
  function hydrateMangaActions(){syncMangaActions()}
  function absorbLibrary(){syncMangaActions()}
  function skeletons(){return `<div class="nx42-manga-grid">${Array.from({length:18},()=>'<div class="nx21-skeleton"></div>').join('')}</div>`}
  function card(raw,libraryItem=null){const item=normalized(raw),name=title(item),image=cover(item),rating=score(item),id=Number(item.id),status=libraryItem?.status||actionState.list.get(id)?.status,favorite=actionState.favorites.has(id);state.items.set(id,item);return `<article class="nx42-manga-card" tabindex="0" data-manga-open="${id}" data-title="${esc(name)}"><div class="nx42-manga-poster">${image?`<img src="${esc(image)}" alt="${esc(name)}" loading="lazy" decoding="async">`:''}${rating?`<span>${svg.star}${rating}</span>`:''}<div class="nx42-manga-actions"><button type="button" data-nx-action-kind="compact" data-manga-list="${id}" class="${status?'active':''}" aria-pressed="${Boolean(status)}" aria-label="${status?`Alterar estado de leitura de ${esc(name)}`:`Adicionar ${esc(name)} à lista`}">${status?svg.check:svg.plus}</button><button type="button" data-nx-action-kind="compact" data-manga-fav="${id}" class="${favorite?'active':''}" aria-pressed="${favorite}" aria-label="${favorite?`Remover ${esc(name)} dos favoritos`:`Favoritar ${esc(name)}`}">${svg.heart}</button></div></div><h3>${esc(name)}</h3><p>${esc([formatLabel(item.format),item.format==='NOVEL'?(libraryItem?.volume_progress||libraryItem?.volumeProgress?`${libraryItem.volume_progress||libraryItem.volumeProgress} volumes lidos`:null):(libraryItem?.progress?`${libraryItem.progress} capítulos lidos`:null),status?statusLabels[status]:null].filter(Boolean).join(' · '))}</p></article>`}
  function wireCards(){document.querySelectorAll('[data-manga-open]').forEach(item=>{item.onclick=event=>{if(event.target.closest('button'))return;go(`/manga/${slug(item.dataset.title)}-${item.dataset.mangaOpen}`)};item.onkeydown=event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('button')){event.preventDefault();item.click()}}});syncMangaActions();void hydrateMangaActions()}
  async function mountLibrary(){if(route()!=='/meus-mangas')return;document.body.classList.add('nx42-manga-active');app.innerHTML=`<main class="nx42-manga-page"><section class="nx42-manga-hero"><div class="shell"><small>SUA BIBLIOTECA</small><h1>Meus Mangás</h1><p>Leituras, progresso, favoritos e notas em um só lugar.</p><div class="nx42-manga-tools"><select id="nx42LibraryFilter"><option value="ALL">Todos</option>${Object.entries(statusLabels).map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select><select id="nx42LibrarySort"><option value="recent">Atualizados recentemente</option><option value="score">Minha nota</option><option value="progress">Progresso</option></select></div></div></section><section class="nx42-manga-body"><div class="shell"><header class="nx42-manga-head"><h2>Minha leitura</h2><a href="/mangas">Explorar catálogo</a></header><div id="nx42MangaLibrary">${skeletons()}</div></div></section></main>`;document.title='Meus Mangás | AniNexus';const ownedRoot=document.querySelector('#nx42MangaLibrary');try{const data=await api('/api/me/manga-library');if(route()!=='/meus-mangas'||ownedRoot!==document.querySelector('#nx42MangaLibrary'))return;state.library=data;absorbLibrary(state.library);paintLibrary();document.querySelector('#nx42LibraryFilter').onchange=paintLibrary;document.querySelector('#nx42LibrarySort').onchange=paintLibrary}catch(error){if(route()!=='/meus-mangas'||ownedRoot!==document.querySelector('#nx42MangaLibrary'))return;if(error.status===401){app.innerHTML='<main class="nx42-manga-page"><section class="nx42-manga-body"><div class="shell"><div class="nx21-empty"><strong>Entre para acessar seus mangás</strong><span>Sua leitura será sincronizada entre os dispositivos.</span><button type="button" data-manga-login>Entrar</button></div></div></section></main>';document.querySelector('[data-manga-login]').onclick=()=>go('/login')}else document.querySelector('#nx42MangaLibrary').innerHTML='<div class="nx21-error"><strong>Sua biblioteca não carregou agora.</strong></div>'}}
  function paintLibrary(){const filter=document.querySelector('#nx42LibraryFilter')?.value||'ALL',sortBy=document.querySelector('#nx42LibrarySort')?.value||'recent',merged=new Map();for(const item of state.library?.list||[])merged.set(Number(item.media_id),{...item,media:normalized(item.media||{id:item.media_id})});for(const item of state.library?.favorites||[]){const id=Number(item.media_id);if(!merged.has(id))merged.set(id,{media_id:id,status:null,media:normalized(item.media||{id})})}let items=[...merged.values()];if(filter!=='ALL')items=items.filter(item=>item.status===filter);items.sort(sortBy==='score'?(a,b)=>(b.score??-1)-(a.score??-1):sortBy==='progress'?(a,b)=>(b.progress||b.volume_progress||b.volumeProgress||0)-(a.progress||a.volume_progress||a.volumeProgress||0):(a,b)=>Date.parse(b.updated_at||0)-Date.parse(a.updated_at||0));state.items.clear();const root=document.querySelector('#nx42MangaLibrary');if(!root)return;root.innerHTML=items.length?`<div class="nx42-manga-grid">${items.map(item=>card(item.media,item)).join('')}</div>`:'<div class="nx21-empty"><strong>Nada nesta categoria</strong><span>Explore o catálogo e adicione sua próxima leitura.</span></div>';wireCards()}
  function mount(){const path=route();if(path==='/mangas'){syncMangaActions();void hydrateMangaActions();return}if(path==='/meus-mangas'&&!window.__ANINEXUS_UNIFIED_LIBRARY__)mountLibrary();else document.body.classList.remove('nx42-manga-active')}
  for(const name of ['manga-media-state-changed','manga-favorite-changed'])document.addEventListener('aninexus:'+name,event=>{
    if(route()!=='/meus-mangas'||!state.library)return;
    const id=Number(event.detail.id),media=state.items.get(id)||{id};
    if(name==='manga-media-state-changed'){
      state.library.list=(state.library.list||[]).filter(row=>Number(row.media_id)!==id);
      if(event.detail.state?.status)state.library.list.unshift({media_id:id,...event.detail.state,updated_at:new Date().toISOString(),media});
    }else{
      state.library.favorites=(state.library.favorites||[]).filter(row=>Number(row.media_id)!==id);
      if(event.detail.favorite)state.library.favorites.unshift({media_id:id,media_type:'MANGA',media});
    }
    paintLibrary();
  });
  addEventListener('aninexus:account-identity-changed',()=>{state.library=null;state.items.clear();if(route()==='/meus-mangas')void mountLibrary()});
  addEventListener('popstate',()=>setTimeout(()=>{mount();syncMangaActions();void hydrateMangaActions()},0));if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mount();syncMangaActions();void hydrateMangaActions()},{once:true});else{mount();syncMangaActions();void hydrateMangaActions()}
})();
