'use strict';
(() => {
  if(window.__ANINEXUS_V42__)return;window.__ANINEXUS_V42__=true;
  const app=document.querySelector('#app'),IS_PAGES=location.hostname.endsWith('github.io'),BASE=IS_PAGES?'/AniNexus':'';
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const avatarMarkup=(user,options={})=>window.AniNexusAvatar?.markup(user,options)||`<img src="${BASE}/assets/avatars/mascot-pink.png" alt="">`;
  const icons={sun:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg>',moon:'<svg viewBox="0 0 24 24"><path d="M20 15.5A8.5 8.5 0 0 1 8.5 4 9 9 0 1 0 20 15.5Z"/></svg>',system:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="14" rx="2"/><path d="M8 22h8M12 18v4"/></svg>',user:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21c.8-5 3.5-7 8-7s7.2 2 8 7"/></svg>',heart:'<svg viewBox="0 0 24 24"><path d="M20.5 8.8c0 5-8.5 10-8.5 10s-8.5-5-8.5-10A4.6 4.6 0 0 1 12 6.4a4.6 4.6 0 0 1 8.5 2.4Z"/></svg>',book:'<svg viewBox="0 0 24 24"><path d="M4 4.5c3.5-.8 6.2-.2 8 1.7v14c-1.8-1.9-4.5-2.5-8-1.7v-14ZM20 4.5c-3.5-.8-6.2-.2-8 1.7v14c1.8-1.9 4.5-2.5 8-1.7v-14Z"/></svg>',bell:'<svg viewBox="0 0 24 24"><path d="M6 10a6 6 0 0 1 12 0c0 5 2 5 2 7H4c0-2 2-2 2-7Z"/><path d="M10 20h4"/></svg>',settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.7-.7-1.7.9-2-2.2-2.2-2 .9-1.7-.7L10.5 2h-3l-.7 2.1-1.7.7-2-.9L1 6.1l.9 2-.7 1.7-2 .7v3l2 .7.7 1.7-.9 2 2.1 2.1 2-.9 1.7.7.7 2.1h3l.7-2.1 1.7-.7 2 .9 2.2-2.1-.9-2 .7-1.7 2.1-.7Z" transform="translate(2) scale(.9)"/></svg>',logout:'<svg viewBox="0 0 24 24"><path d="M10 4H5v16h5M14 8l4 4-4 4M8 12h10"/></svg>',play:'<svg viewBox="0 0 24 24"><path d="m9 6 9 6-9 6V6Z"/></svg>',arrow:'<svg viewBox="0 0 24 24"><path d="M5 12h13M14 7.5 18.5 12 14 16.5"/></svg>',plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',star:'<svg viewBox="0 0 24 24"><path d="m12 3 2.8 5.5 6.1.9-4.4 4.3 1 6.1-5.5-2.9-5.5 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>',close:'<svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>'};
  function route(){const url=new URL(location.href),restored=url.searchParams.get('p');if(restored)return restored.split('?')[0].replace(/\/+$/,'')||'/';let path=url.pathname;if(IS_PAGES)path=path.replace(/^\/AniNexus/,'')||'/';return path.replace(/\/+$/,'')||'/'}
  function go(path){if(IS_PAGES)location.assign(`${BASE}/?build=44.35.0&p=${encodeURIComponent(path)}`);else if(!window.AniNexusGo?.(path))location.assign(path)}
  async function requireAccount(){const auth=window.AniNexusAuth;if(typeof auth?.requireAccount==='function')return auth.requireAccount();go('/login');return null}
  function themeChoice(){try{return localStorage.getItem('aninexus:theme')||'system'}catch{return'system'}}
  function applyTheme(choice){const resolved=choice==='system'?(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'):choice;try{localStorage.setItem('aninexus:theme',choice)}catch{}document.documentElement.dataset.theme=resolved;document.documentElement.style.colorScheme=resolved;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',resolved==='light'?'#fffafb':'#08060b');document.querySelectorAll('[data-nx42-theme]').forEach(button=>button.classList.toggle('active',button.dataset.nx42Theme===choice));dispatchEvent(new CustomEvent('aninexus:theme-changed',{detail:{choice,resolved}}))}
  function themeCard(){return `<section class="nx42-theme-card" aria-label="Aparência"><header><strong>Aparência</strong><span>Escolha como prefere ver</span></header><div class="nx42-theme-options"><button type="button" data-nx42-theme="light">${icons.sun}Claro</button><button type="button" data-nx42-theme="dark">${icons.moon}Escuro</button><button type="button" data-nx42-theme="system">${icons.system}Automático</button></div></section>`}
  function paintCompactTheme(button){const dark=document.documentElement.dataset.theme==='dark';button.innerHTML=dark?icons.moon:icons.sun;button.setAttribute('aria-label',dark?'Ativar tema claro':'Ativar tema escuro');button.title=dark?'Ativar tema claro':'Ativar tema escuro'}
  function mountTheme(){const host=document.querySelector('.drawer-content');if(!host)return;const compact=host.querySelector('[data-nx-drawer-theme]');if(compact){host.querySelector('.nx42-theme-card')?.remove();if(!compact.dataset.nxThemeBound){compact.dataset.nxThemeBound='1';compact.onclick=()=>{applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');paintCompactTheme(compact)};addEventListener('aninexus:theme-changed',()=>paintCompactTheme(compact))}applyTheme(themeChoice());paintCompactTheme(compact);return}if(host.querySelector('.nx42-theme-card'))return;host.insertAdjacentHTML('beforeend',themeCard());host.querySelectorAll('[data-nx42-theme]').forEach(button=>button.onclick=()=>applyTheme(button.dataset.nx42Theme));applyTheme(themeChoice())}
  matchMedia('(prefers-color-scheme:light)').addEventListener?.('change',()=>{if(themeChoice()==='system')applyTheme('system')});

  let account=null,menu=null;
  addEventListener('aninexus:account-identity-changed',event=>{if(event.detail&&Object.prototype.hasOwnProperty.call(event.detail,'user')){account=event.detail.user||null;document.querySelectorAll('.nx42-impressions').forEach(section=>section.dispatchEvent(new Event('nx42:identity')))}});
  async function accountData(){if(account)return account;try{account=window.AniNexusAccountData?await window.AniNexusAccountData():(await window.AniNexusAuth?.api?.('/api/me'))?.user||null}catch{}return account}
  function closeAccount(){menu?.remove();menu=null;document.removeEventListener('pointerdown',outsideAccount,true)}
  function outsideAccount(event){if(menu&&!menu.contains(event.target)&&!event.target.closest('.nx38-account-chip'))closeAccount()}
  async function openAccount(chip){if(menu){closeAccount();return}const user=await accountData(),rect=chip.getBoundingClientRect(),name=user?.displayName||chip.textContent.trim()||'Minha conta',handle=user?.username?`@${user.username}`:'Conta AniNexus',identity=user||{displayName:name,avatarUrl:chip.querySelector('img')?.src||''};menu=document.createElement('section');menu.className='nx42-account-menu';menu.setAttribute('role','menu');menu.style.top=`${Math.round(rect.bottom+8)}px`;menu.style.right=`${Math.max(10,Math.round(innerWidth-rect.right))}px`;menu.innerHTML=`<header><i>${avatarMarkup(identity,{name})}</i><div><strong>${esc(name)}</strong><span>${esc(handle)}</span></div></header><nav><button type="button" data-nx42-go="/minha-biblioteca">${icons.book}Minha biblioteca</button>${user?.username?`<button type="button" data-nx42-go="/u/${encodeURIComponent(user.username)}">${icons.user}Meu perfil público</button>`:''}<button type="button" data-nx42-go="/minha-conta">${icons.settings}Conta e configurações</button><button type="button" data-nx42-logout class="danger">${icons.logout}Sair</button></nav>`;document.body.append(menu);menu.querySelectorAll('[data-nx42-go]').forEach(button=>button.onclick=()=>{closeAccount();go(button.dataset.nx42Go)});menu.querySelector('[data-nx42-logout]').onclick=async()=>{await window.AniNexusAuth?.signOut?.();closeAccount();location.assign('/')};setTimeout(()=>document.addEventListener('pointerdown',outsideAccount,true),0)}
  async function tuneAccountChip(chip){if(chip.dataset.nx42)return;chip.dataset.nx42='1';const user=await accountData();const holder=chip.querySelector('i');if(holder)holder.innerHTML=avatarMarkup(user||{avatarUrl:chip.querySelector('img')?.src},{name:user?.displayName||user?.username||'membro'});chip.setAttribute('aria-haspopup','menu');chip.setAttribute('aria-label','Abrir menu da conta');chip.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();openAccount(chip)},true)}

  function cleanVisibleText(root=document){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode(node){if(!node.nodeValue?.trim()||node.parentElement?.closest('script,style,textarea,input,.nx40-source-flow'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const node of nodes){let value=node.nodeValue;value=value.replace(/\bno ep\.?\s*(\d+)/gi,'no episódio $1').replace(/\b(\d+)\s+eps\b/gi,'$1 episódios').replace(/\bep\.?\s*(\d+)/gi,'episódio $1');if(value!==node.nodeValue)node.nodeValue=value}}
  function mediaTitle(m){return m?.title?.english||m?.title?.userPreferred||m?.title?.romaji||m?.title||'Título'}
  function mediaCover(m){return m?.coverImage?.extraLarge||m?.coverImage?.large||m?.cover||''}
  function mediaScore(m){if(m?.metricsSource!=='aninexus')return'';const score=m?.averageScore?Number(m.averageScore)/10:Number(m?.score);return Number.isFinite(score)&&score>0?score.toFixed(1).replace('.0',''):''}
  function mediaSlug(value='titulo'){return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90)||'titulo'}
  function rankCard(m,index,type='manga'){const title=mediaTitle(m),cover=mediaCover(m),score=mediaScore(m),path=`/${type}/${mediaSlug(title)}-${Number(m.id)}`,rank=String(index+1).padStart(2,'0'),format={MANGA:'Mangá',NOVEL:'Light novel',ONE_SHOT:'One-shot'}[String(m.format||'').toUpperCase()]||'Mangá',status={RELEASING:'Em publicação',FINISHED:'Concluído',HIATUS:'Em hiato',CANCELLED:'Cancelado'}[String(m.status||'').toUpperCase()]||'',year=Number(m.startDate?.year||m.seasonYear)||null,facts=[format,year,status].filter(Boolean),ratings=Math.max(0,Number(m.ratingCount)||0),ratingLabel=ratings===1?'1 avaliação':`${ratings.toLocaleString('pt-BR')} avaliações`;return `<a class="nx35-rank nx45-rank-card nx45-rank-manga rank-${index+1}" href="${esc(path)}" data-nx42-media="${Number(m.id)}" data-nx42-type="${type}" data-title="${esc(title)}" aria-label="Abrir ${esc(title)}"><span class="nx35-rank-num" aria-hidden="true">${rank}</span><div class="nx35-rank-cover">${cover?`<img loading="lazy" decoding="async" src="${esc(cover)}" alt="${esc(title)}">`:'<span class="nx45-rank-cover-empty">AN</span>'}<span class="nx45-manga-mark" aria-hidden="true">${icons.book}</span></div><div class="nx35-rank-copy"><small>LEITURA #${rank}</small><h3>${esc(title)}</h3><p class="nx45-rank-facts">${facts.map(fact=>`<span>${esc(fact)}</span>`).join('')}</p><footer>${score?`<b aria-label="Nota ${esc(score)}">${icons.star}<span>${esc(score)}</span></b>`:''}<span>${esc(ratingLabel)}</span><i aria-hidden="true">${icons.arrow}</i></footer></div></a>`}
  async function mountHomeExtras(){if(route()!=='/'||!document.querySelector('.nx35-home')||document.querySelector('#nx42TopManga'))return;const animeRanking=document.querySelector('#nx35Top')?.closest('.nx35-section');if(animeRanking){const section=document.createElement('section');section.className='nx35-section tonal nx42-home-ranking nx45-manga-ranking';section.innerHTML=`<div class="nx35-shell"><div class="nx35-head"><div><small>RANKING DE LEITURA</small><h2>Top 10 <em>Mangás</em></h2><p>Uma estante própria, construída somente pelas notas dos leitores do AniNexus.</p></div><a href="/mangas">Ver catálogo ${icons.arrow}</a></div><div id="nx42TopManga" class="nx35-placeholder"><div class="nx35-skeleton-row"></div></div></div>`;animeRanking.insertAdjacentElement('afterend',section)}
    try{let items=[];if(!IS_PAGES){const response=await fetch('/api/reading?page=1&perPage=10&format=MANGA&sort=SCORE',{headers:{accept:'application/json'}});if(response.ok)items=((await response.json()).items||[]).filter(item=>item.metricsSource==='aninexus'&&Number(item.ratingCount)>0)}const root=document.querySelector('#nx42TopManga');if(root)root.innerHTML=items.length?`<div class="nx35-edge"><div class="nx35-rail nx35-rank-rail">${items.slice(0,10).map((m,i)=>rankCard(m,i)).join('')}</div></div>`:`<div class="nx45-ranking-empty"><span aria-hidden="true">${icons.book}</span><div><strong>O ranking de leitura está começando.</strong><p>As primeiras posições aparecem conforme a comunidade avalia seus mangás.</p></div><a href="/mangas">Explorar mangás ${icons.arrow}</a></div>`}catch{document.querySelector('#nx42TopManga')?.replaceChildren()}
    const community=document.querySelector('#nx35Community')?.closest('.nx35-section');if(community&&!document.querySelector('#nx42Trailers')){const section=document.createElement('section');section.className='nx35-section nx42-trailers-section';section.innerHTML=`<div class="nx35-shell"><div class="nx35-head"><div><small>VÍDEOS</small><h2>Últimos <em>Trailers</em></h2><p>Os materiais promocionais mais recentes, reproduzidos sem sair do AniNexus.</p></div><a href="/noticias">Ver notícias ${icons.arrow}</a></div><div class="nx35-edge"><div id="nx42Trailers" class="nx35-rail nx42-trailer-rail"><div class="nx35-skeleton-row"></div></div></div></div>`;community.insertAdjacentElement('beforebegin',section);loadTrailers()}
  }
  function trailerRelative(value){const time=Date.parse(value||'');if(!Number.isFinite(time))return'';const elapsed=Math.max(0,Date.now()-time);if(elapsed<3_600_000)return`há ${Math.max(1,Math.floor(elapsed/60_000))} min`;if(elapsed<86_400_000)return`há ${Math.floor(elapsed/3_600_000)} h`;const days=Math.floor(elapsed/86_400_000);return days===1?'ontem':`há ${days} dias`}
  function normalizedTrailer(item){const videoId=String(item?.videoId||item?.id||''),publishedAt=String(item?.publishedAt||''),age=Date.now()-Date.parse(publishedAt);if(!/^[A-Za-z0-9_-]{11}$/.test(videoId)||!Number.isFinite(age)||age< -36*3_600_000||age>21*86_400_000)return null;return{videoId,title:String(item?.title||item?.articleTitle||'Novo trailer de anime').slice(0,180),kind:['TRAILER','TEASER','PV'].includes(String(item?.kind||'').toUpperCase())?String(item.kind).toUpperCase():'TRAILER',publishedAt,source:String(item?.source||'').slice(0,80),thumbnail:String(item?.thumbnail||`https://i.ytimg.com/vi/${videoId}/maxresdefault.jpg`),fallbackImage:String(item?.fallbackImage||''),articlePath:String(item?.articlePath||'')}}
  async function trailerData(){
    if(!IS_PAGES)try{const response=await fetch('/api/trailers?limit=9',{headers:{accept:'application/json'}});if(response.ok){const data=await response.json();if(data?.items?.length)return data.items}}catch{}
    try{const response=await fetch(`${BASE}/data/trailers.json?v=44.16.2`,{headers:{accept:'application/json'},cache:'no-store'});if(response.ok)return(await response.json())?.items||[]}catch{}
    return[];
  }
  function trailerCard(item){const fallback=[`https://i.ytimg.com/vi/${item.videoId}/hqdefault.jpg`,item.fallbackImage].filter(Boolean),encoded=encodeURIComponent(JSON.stringify(fallback)),fresh=trailerRelative(item.publishedAt);return `<button type="button" class="nx42-trailer" data-nx42-trailer="${esc(item.videoId)}" data-nx42-trailer-title="${esc(item.title)}" aria-label="Assistir ${esc(item.title)} no AniNexus"><span class="nx42-trailer-media"><img src="${esc(item.thumbnail)}" data-nx42-trailer-image data-nx42-trailer-fallbacks="${esc(encoded)}" alt="" loading="lazy" decoding="async"><i aria-hidden="true">${icons.play}</i><b>${esc(item.kind)}</b></span><span class="nx42-trailer-copy"><strong>${esc(item.title)}</strong><small>${esc(fresh||'Publicado recentemente')}</small></span></button>`}
  function bindTrailerImages(root){root.querySelectorAll('[data-nx42-trailer-image]').forEach(image=>{if(image.dataset.nx42Bound)return;image.dataset.nx42Bound='1';let queue=[];try{queue=JSON.parse(decodeURIComponent(image.dataset.nx42TrailerFallbacks||'%5B%5D'))}catch{}const fail=()=>{const next=queue.shift();if(next){image.dataset.nx42TrailerFallbacks=encodeURIComponent(JSON.stringify(queue));image.src=next;return}image.closest('.nx42-trailer-media')?.classList.add('is-missing');image.remove()};image.addEventListener('error',fail);if(image.complete&&!image.naturalWidth)queueMicrotask(fail)})}
  async function loadTrailers(){const root=document.querySelector('#nx42Trailers');if(!root)return;try{const items=(await trailerData()).map(normalizedTrailer).filter(Boolean).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,9);if(!root.isConnected)return;root.innerHTML=items.length?items.map(trailerCard).join(''):'<div class="nx35-data-empty"><strong>Novos trailers serão publicados aqui.</strong></div>';bindTrailerImages(root);window.AniNexusRails?.refresh?.()}catch{root.innerHTML='<div class="nx35-data-empty"><strong>Os trailers estão sendo atualizados.</strong></div>'}}

  let trailerModal=null,trailerReturnFocus=null;
  function closeTrailer(){if(!trailerModal)return;const modal=trailerModal;trailerModal=null;modal.querySelector('iframe')?.setAttribute('src','about:blank');document.body.classList.remove('nx42-trailer-open');modal.classList.remove('is-open');modal.classList.add('is-closing');const finish=()=>{modal.remove();trailerReturnFocus?.focus?.({preventScroll:true});trailerReturnFocus=null};if(matchMedia('(prefers-reduced-motion: reduce)').matches)finish();else setTimeout(finish,180)}
  function openTrailer(button){const videoId=String(button?.dataset?.nx42Trailer||''),title=String(button?.dataset?.nx42TrailerTitle||'Trailer');if(!/^[A-Za-z0-9_-]{11}$/.test(videoId))return;closeTrailer();trailerReturnFocus=button;const layer=document.createElement('div');layer.className='nx42-trailer-modal';layer.innerHTML=`<button class="nx42-trailer-backdrop" type="button" data-nx42-trailer-close aria-label="Fechar trailer"></button><section class="nx42-trailer-dialog" role="dialog" aria-modal="true" aria-labelledby="nx42TrailerTitle" tabindex="-1"><header><div><small>REPRODUZINDO NO ANINEXUS</small><h2 id="nx42TrailerTitle">${esc(title)}</h2></div><button type="button" data-nx42-trailer-close aria-label="Fechar trailer">${icons.close}</button></header><div class="nx42-trailer-player"><iframe src="https://www.youtube-nocookie.com/embed/${encodeURIComponent(videoId)}?autoplay=1&rel=0&playsinline=1" title="Trailer: ${esc(title)}" allow="autoplay; encrypted-media; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div></section>`;document.body.append(layer);trailerModal=layer;document.body.classList.add('nx42-trailer-open');requestAnimationFrame(()=>layer.classList.add('is-open'));layer.querySelector('.nx42-trailer-dialog').focus();layer.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();closeTrailer();return}if(event.key!=='Tab')return;const focusable=[...layer.querySelectorAll('button,iframe')].filter(node=>!node.disabled),first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}})}

  const GENRES={Ação:'Action',Aventura:'Adventure',Comédia:'Comedy',Drama:'Drama',Fantasia:'Fantasy',Terror:'Horror',Mistério:'Mystery',Romance:'Romance','Ficção Científica':'Sci-Fi',Cotidiano:'Slice of Life',Esportes:'Sports',Sobrenatural:'Supernatural',Suspense:'Thriller',Psicológico:'Psychological',Música:'Music',Mecha:'Mecha'};
  function enhanceDetail(){
    const match=route().match(/^\/(anime|manga)\/.+-(\d+)$/);if(!match||!document.querySelector('.nx22-detail')||document.querySelector('.nx22-fail'))return;
    const type=match[1]==='manga'?'MANGA':'ANIME',catalog=type==='MANGA'?'/mangas':'/animes/catalogo';
    const chips=document.querySelector('.nx22-chips');
    chips?.querySelectorAll('span').forEach(span=>{const genre=GENRES[span.textContent.trim()];if(!genre)return;const link=document.createElement('a');link.className='genre';link.href=catalog;link.textContent=span.textContent;link.dataset.nx22Genre=genre;link.onclick=()=>{try{sessionStorage.setItem('nx23:catalog:incoming',JSON.stringify({genre}))}catch{}};span.replaceWith(link)});
    const stats=document.querySelector('.nx22-stats');
    if(stats&&!stats.dataset.community){
      stats.dataset.community='loading';
      fetch(`/api/${match[1]}/${Number(match[2])}/rating`,{headers:{accept:'application/json'}}).then(response=>response.ok?response.json():null).then(data=>{
        const cell=stats.firstElementChild;if(!cell||!data?.votes)return;
        const score=Number(data.score);if(!Number.isFinite(score))return;
        cell.querySelector('strong').textContent=score.toFixed(2);
        cell.querySelectorAll('.nx22-average-star').forEach((star,index)=>star.style.setProperty('--nx22-star-fill',`${Math.max(0,Math.min(100,(score-index*2)*50))}%`));
      }).catch(()=>{}).finally(()=>stats.dataset.community='ready');
    }
  }
  async function mountImpressions(type,requestedHost){
    const match=route().match(type==='ANIME'?/^\/anime\/.+-(\d+)$/:/^\/manga\/.+-(\d+)$/),host=requestedHost||document.querySelector('#nx22Impressions');
    if(!match||!host||host.querySelector('.nx42-impressions')||document.querySelector('.nx22-fail'))return;
    const id=Number(match[1]),endpoint=`/api/${type==='ANIME'?'anime':'manga'}/${id}/impressions`;
    host.innerHTML='';
    const section=document.createElement('section');section.className='nx42-impressions';section.innerHTML=`<div class="nx42-impressions-head"><div><small>COMUNIDADE</small><h2>Impressões dos membros</h2></div></div><div class="nx42-impression-access" aria-live="polite"></div><div class="nx42-impression-list" aria-live="polite">Carregando…</div>`;host.append(section);
    const access=section.querySelector('.nx42-impression-access'),list=section.querySelector('.nx42-impression-list');
    async function load(){try{const response=await fetch(endpoint,{headers:{accept:'application/json'}}),data=response.ok?await response.json():{items:[]};list.innerHTML=(data.items||[]).length?(data.items||[]).map(item=>`<article class="nx42-impression"><header>${item.avatar_url?`<img src="${esc(item.avatar_url)}" alt="">`:`<i>${esc(String(item.display_name||item.username||'?').charAt(0))}</i>`}<a href="/u/${encodeURIComponent(item.username)}">@${esc(item.username)}</a><time>${new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium'}).format(new Date(item.created_at))}</time></header><p class="${item.spoiler?'nx42-spoiler':''}" title="Toque para revelar">${esc(item.body)}</p></article>`).join(''):'<div class="nx35-data-empty"><strong>Seja a primeira pessoa a deixar uma impressão.</strong></div>';list.querySelectorAll('.nx42-spoiler').forEach(item=>item.onclick=()=>item.classList.toggle('revealed'))}catch{list.textContent='As impressões não carregaram agora.'}}
    function renderComposer(user){
      if(!section.isConnected)return;
      if(!user){access.innerHTML='<button type="button" data-nx42-impression-login>Entre na sua conta para compartilhar uma impressão</button>';access.querySelector('button').onclick=()=>go('/login');return}
      access.innerHTML='<form class="nx42-impression-form"><textarea maxlength="1200" placeholder="Compartilhe sua impressão sobre esta obra" aria-label="Sua impressão"></textarea><footer><label><input type="checkbox" name="spoiler"> Contém spoiler</label><button type="submit">Publicar impressão</button></footer></form>';
      access.querySelector('form').onsubmit=async event=>{event.preventDefault();const textarea=event.currentTarget.querySelector('textarea'),button=event.currentTarget.querySelector('button'),body=textarea.value.trim();if(!body)return;button.disabled=true;try{await window.AniNexusAuth.api(endpoint,{method:'POST',body:JSON.stringify({body,spoiler:event.currentTarget.elements.spoiler.checked})});textarea.value='';await load()}catch(error){if(error?.status===401)go('/login')}finally{button.disabled=false}};
    }
    section.addEventListener('nx42:identity',()=>renderComposer(account));
    renderComposer(await accountData());
    load();
  }

  async function mountNotifications(){if(route().split('#')[0]!=='/minha-conta'||document.querySelector('.nx42-notifications'))return;const shell=document.querySelector('.nx38-account-shell');if(!shell)return;const section=document.createElement('section');section.className='nx42-notifications';section.id='notificacoes';section.innerHTML='<h2>Notificações</h2><p>Carregando…</p>';shell.append(section);try{const data=await window.AniNexusAuth?.api?.('/api/me/notifications?limit=20'),items=data?.items||[];section.innerHTML=`<h2>Notificações</h2>${items.length?items.map(item=>`<article class="nx42-notification${item.read_at?' read':''}" data-notification="${esc(item.id)}"><i></i><div><strong>${esc(item.title)}</strong>${item.body?`<p>${esc(item.body)}</p>`:''}</div><time>${new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(item.created_at))}</time></article>`).join(''):'<p>Você está em dia. Novidades da sua lista aparecerão aqui.</p>'}`;section.querySelectorAll('[data-notification]:not(.read)').forEach(row=>row.onclick=async()=>{await window.AniNexusAuth.api(`/api/me/notifications/${row.dataset.notification}/read`,{method:'POST'});row.classList.add('read')})}catch{section.innerHTML='<h2>Notificações</h2><p>Não foi possível consultar agora.</p>'}}

  function consent(){if(IS_PAGES)return;try{if(localStorage.getItem('aninexus:privacy:v1'))return}catch{}const card=document.createElement('section');card.className='nx42-consent';card.setAttribute('role','dialog');card.setAttribute('aria-label','Preferências de privacidade');card.innerHTML='<strong>Privacidade no AniNexus</strong><p>Usamos armazenamento necessário para manter login, tema e sua lista. Métricas opcionais só serão usadas com sua escolha.</p><div><button type="button" data-consent="necessary">Somente necessárias</button><button class="primary" type="button" data-consent="analytics">Permitir métricas</button></div>';document.body.append(card);card.querySelectorAll('[data-consent]').forEach(button=>button.onclick=()=>{try{localStorage.setItem('aninexus:privacy:v1',JSON.stringify({analytics:button.dataset.consent==='analytics',at:Date.now()}))}catch{}card.remove()})}

  function enhance(){if(route()!=='/'&&trailerModal)closeTrailer();mountTheme();document.querySelectorAll('.nx38-account-chip').forEach(tuneAccountChip);cleanVisibleText(app);const footerCopy=document.querySelector('.footer-about p');if(footerCopy)footerCopy.textContent='Seu espaço para organizar listas, acompanhar lançamentos, avaliar obras e conversar com a comunidade.';mountHomeExtras();enhanceDetail();mountNotifications()}
  const observer=new MutationObserver(records=>{if(records.some(record=>[...record.addedNodes].some(node=>node.nodeType===1))){clearTimeout(observer.timer);observer.timer=setTimeout(enhance,20)}});observer.observe(document.documentElement,{subtree:true,childList:true});
  document.addEventListener('click',event=>{const close=event.target.closest('[data-nx42-trailer-close]');if(close){event.preventDefault();closeTrailer();return}const trailer=event.target.closest('[data-nx42-trailer]');if(trailer){event.preventDefault();openTrailer(trailer)}});
  document.addEventListener('click',event=>{const media=event.target.closest('[data-nx42-media]');if(media&&!event.target.closest('button,a'))go(`/${media.dataset.nx42Type}/${String(media.dataset.title||'titulo').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}-${media.dataset.nx42Media}`)});
  addEventListener('popstate',()=>{closeTrailer();setTimeout(enhance,30)});addEventListener('aninexus:home-v34-ready',()=>setTimeout(mountHomeExtras,20));addEventListener('aninexus:route-ready',()=>setTimeout(enhance,20));
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{enhance();setTimeout(consent,800)},{once:true});else{enhance();setTimeout(consent,800)}
})();
