'use strict';
(() => {
  const app=document.querySelector('#app'); if(!app)return;
  const IS_PAGES=location.hostname.endsWith('github.io');
  const BASE=IS_PAGES?'/AniNexus':'';
  const CONTACT='contato@aninexus.com.br';
  const UPDATED='25 de agosto de 2026';
  const LEGAL=new Set(['/termos-de-uso','/politica-de-privacidade','/dmca']);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const href=p=>`${BASE}${p}`;
  function route(){let p=location.pathname;if(IS_PAGES)p=p.replace(/^\/AniNexus/,'')||'/';const q=new URLSearchParams(location.search).get('p');if(q)p=q.split('?')[0];return p.replace(/\/+$/,'')||'/'}
  function tabs(active){return `<nav class="nx-legal-tabs" aria-label="Documentos legais"><a href="${href('/termos-de-uso')}" data-nx-legal="/termos-de-uso" class="${active==='/termos-de-uso'?'active':''}">Termos de Serviço</a><a href="${href('/politica-de-privacidade')}" data-nx-legal="/politica-de-privacidade" class="${active==='/politica-de-privacidade'?'active':''}">Política de Privacidade</a><a href="${href('/dmca')}" data-nx-legal="/dmca" class="${active==='/dmca'?'active':''}">DMCA</a></nav>`}
  function head(path,title,overline){return `<header class="nx-legal-head"><div class="nx-legal-shell"><div class="nx-legal-overline">${overline}</div><h1>${title}</h1><div class="nx-legal-updated">Última atualização: ${UPDATED}</div>${tabs(path)}</div></header>`}
  const sec=(id,num,title,body)=>`<section class="nx-legal-section" id="${id}"><h2><span class="num">${num}</span>${title}</h2>${body}</section>`;
  const p=t=>`<p>${t}</p>`;
  function shell(path,title,overline,intro,sections,toc,after=''){return `<div class="nx-legal">${head(path,title,overline)}<div class="nx-legal-shell nx-legal-layout"><main class="nx-legal-main">${intro}${sections}${after}</main><aside class="nx-legal-side"><strong>Neste documento</strong>${toc.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}<div class="minor"><a href="mailto:${CONTACT}">${CONTACT}</a></div></aside></div></div>`}

  function terms(){
    const intro=`<p class="nx-legal-intro"><strong>Estes Termos de Serviço regulam o acesso e o uso do AniNexus.</strong> Ao criar uma conta, publicar conteúdo, utilizar listas pessoais ou continuar navegando pela plataforma, você declara ter lido e aceitado estas condições.</p><p class="nx-legal-intro">O AniNexus é um serviço de catálogo, descoberta, acompanhamento e comunidade voltado a animes, mangás e light novels. A plataforma não se apresenta como serviço de streaming e não hospeda episódios ou filmes protegidos.</p><div class="nx-legal-note"><span></span><div><strong>Leitura importante</strong><span>Se você não concordar com estes Termos, não utilize recursos que dependam de conta ou publicação de conteúdo. Alguns recursos poderão ter regras adicionais exibidas no momento do uso.</span></div></div>`;
    const sections=
      sec('servico','01','Natureza do serviço',p('O AniNexus organiza informações sobre obras, temporadas, calendários, estúdios, disponibilidade em serviços oficiais, notícias, listas e dados de comunidade. Informações podem ser atualizadas, corrigidas, reordenadas ou removidas a qualquer momento para preservar precisão, segurança ou conformidade.')+p('Links para serviços externos são fornecidos por conveniência. A disponibilidade, preço, catálogo, qualidade e políticas desses serviços são responsabilidade de seus respectivos operadores.'))+
      sec('contas','02','Contas e segurança',p('Alguns recursos exigem uma conta. Você deve fornecer informações verdadeiras, manter sua senha em sigilo e adotar medidas razoáveis para impedir acesso não autorizado. Você é responsável pelas atividades realizadas em sua conta, salvo quando a lei determinar de forma diferente.')+p('Podemos limitar sessões, exigir nova autenticação, bloquear tentativas suspeitas ou encerrar sessões para proteger usuários e a infraestrutura. Se perceber uso indevido da sua conta, entre em contato conosco.'))+
      sec('idade','03','Idade e capacidade',p('Ao utilizar o AniNexus, você declara possuir capacidade legal para aceitar estes Termos ou estar utilizando a plataforma com autorização e supervisão do responsável legal quando isso for exigido. Recursos comunitários podem receber restrições adicionais de idade e moderação.'))+
      sec('uso','04','Uso permitido e condutas proibidas',p('Você pode utilizar o AniNexus para fins pessoais, informativos e comunitários compatíveis com a finalidade do serviço. É proibido usar a plataforma para fraude, assédio, ameaça, discurso ilegal, spam, manipulação coordenada, violação de direitos autorais, exploração de vulnerabilidades, raspagem abusiva, tentativa de acesso a contas de terceiros, sobrecarga deliberada da infraestrutura ou distribuição de malware.')+p('Automação, coleta em massa ou integração com o AniNexus poderá depender de autorização, limites técnicos e regras próprias. Medidas de proteção e rate limiting não devem ser contornadas.'))+
      sec('comunidade','05','Conteúdo da comunidade',p('Comentários, avaliações, listas públicas, tópicos, notícias editoriais e demais materiais enviados por usuários continuam pertencendo aos respectivos autores. Ao publicá-los, você concede ao AniNexus uma licença não exclusiva, gratuita e limitada ao necessário para armazenar, exibir, formatar, distribuir dentro da plataforma, moderar e operar o recurso em que o conteúdo foi enviado.')+p('Você declara possuir os direitos necessários sobre o que publicar e não deve enviar material que viole direitos de terceiros, leis aplicáveis ou as regras de comunidade. Conteúdo pode ser ocultado, restringido ou removido após moderação, denúncia válida, ordem legal ou risco de segurança.'))+
      sec('propriedade','06','Propriedade intelectual e materiais de terceiros',p('A marca AniNexus, sua identidade visual, software, textos editoriais próprios, organização do produto e elementos originais da plataforma são protegidos conforme a legislação aplicável. O uso do serviço não transfere ao usuário qualquer direito de propriedade sobre esses elementos.')+p('Títulos de obras, personagens, imagens promocionais, marcas, trailers, sinopses e outros materiais de terceiros pertencem aos respectivos titulares. Sua exibição no AniNexus tem finalidade de identificação, informação, crítica, descoberta e divulgação, conforme aplicável. Solicitações relacionadas a direitos autorais devem utilizar a página de <a href="'+href('/dmca')+'" data-nx-legal="/dmca">DMCA e propriedade intelectual</a>.'))+
      sec('noticias','07','Notícias, informações e spoilers',p('Notícias e dados podem combinar curadoria editorial, informações públicas, atualizações automatizadas e contribuições da comunidade. Embora busquemos precisão e atualização, erros, atrasos, alterações de agenda ou informações incompletas podem ocorrer.')+p('Conteúdo marcado como spoiler deve respeitar os mecanismos de ocultação disponibilizados. Não garantimos que todo spoiler publicado por terceiros será identificado imediatamente.'))+
      sec('moderacao','08','Moderação, denúncias e medidas de proteção',p('Podemos analisar denúncias, limitar alcance, ocultar conteúdo, bloquear funcionalidades, suspender contas ou encerrar acesso quando houver violação destes Termos, risco à segurança, determinação legal, reincidência ou abuso grave. Sempre que razoável e juridicamente permitido, consideraremos contexto, gravidade e histórico.')+p('A existência de moderação não significa que o AniNexus revise previamente todo conteúdo de usuário.'))+
      sec('disponibilidade','09','Disponibilidade e alterações do serviço',p('Recursos podem ser alterados, testados, interrompidos ou descontinuados. Manutenções, falhas de provedores, problemas de rede e eventos fora do nosso controle podem causar indisponibilidade temporária. Não garantimos funcionamento ininterrupto ou ausência absoluta de erros.')+p('Podemos modificar estrutura de dados, interface, limites de uso, integrações e recursos para melhorar segurança, desempenho ou experiência.'))+
      sec('responsabilidade','10','Responsabilidade',p('O AniNexus é uma plataforma informativa e comunitária. Decisões sobre contratação de serviços externos, compras, assinaturas, classificação indicativa ou consumo de conteúdo são de responsabilidade do usuário. Na máxima extensão permitida pela legislação aplicável, não nos responsabilizamos por atos de terceiros, conteúdo externo, indisponibilidade de serviços de terceiros ou perdas decorrentes de uso contrário a estes Termos.')+p('Nada nesta seção exclui responsabilidades que não possam ser afastadas por lei, inclusive direitos assegurados ao consumidor quando aplicáveis.'))+
      sec('encerramento','11','Suspensão, encerramento e exclusão de conta',p('Você poderá deixar de utilizar o serviço a qualquer momento. Quando a funcionalidade estiver disponível, poderá solicitar exclusão da conta e de dados associados, observadas retenções necessárias para cumprimento legal, segurança, prevenção de fraude ou exercício de direitos.')+p('Podemos suspender ou encerrar contas nos casos previstos nestes Termos. Determinados registros técnicos ou de moderação poderão ser preservados pelo período necessário às finalidades legítimas e obrigações aplicáveis.'))+
      sec('alteracoes','12','Alterações destes Termos',p('Podemos atualizar estes Termos para refletir mudanças no produto, na legislação ou em práticas de segurança. A data de atualização será indicada no início da página. Mudanças relevantes poderão ser comunicadas por aviso na plataforma, e-mail ou outro canal apropriado quando necessário.'))+
      sec('lei','13','Legislação e contato',p('Estes Termos são interpretados de acordo com a legislação brasileira, sem prejuízo de normas de proteção ao consumidor e regras de competência obrigatória quando aplicáveis. Dúvidas sobre estes Termos podem ser encaminhadas para <a href="mailto:'+CONTACT+'">'+CONTACT+'</a>.'));
    const toc=[['servico','Natureza do serviço'],['contas','Contas e segurança'],['uso','Uso permitido'],['comunidade','Conteúdo da comunidade'],['propriedade','Propriedade intelectual'],['moderacao','Moderação'],['responsabilidade','Responsabilidade'],['encerramento','Encerramento'],['lei','Legislação e contato']];
    return shell('/termos-de-uso','Termos de Serviço','AniNexus · documento institucional',intro,sections,toc);
  }

  function privacy(){
    const intro=`<p class="nx-legal-intro"><strong>Esta Política explica como o AniNexus trata dados pessoais e informações técnicas relacionadas ao uso da plataforma.</strong> Ela se aplica ao site, contas, listas pessoais, comunidade, formulários, notícias, recursos de segurança e demais serviços operados pelo AniNexus.</p><p class="nx-legal-intro">Tratamos apenas os dados necessários para operar, proteger e melhorar o serviço, cumprir obrigações legais e oferecer os recursos solicitados pelo usuário.</p><div class="nx-legal-note"><span></span><div><strong>Privacidade por padrão</strong><span>O AniNexus não tem como atividade a venda de dados pessoais. O compartilhamento ocorre quando necessário à operação, segurança, cumprimento legal ou mediante escolha do usuário.</span></div></div>`;
    const sections=
      sec('controlador','01','Quem trata os dados',p('Para fins desta Política, AniNexus é o responsável pela operação da plataforma e pelas decisões relacionadas ao tratamento descrito aqui. Enquanto os dados cadastrais definitivos da operação não forem publicados, solicitações de privacidade podem ser encaminhadas para <a href="mailto:'+CONTACT+'">'+CONTACT+'</a>.'))+
      sec('dados','02','Dados que podemos coletar',`<dl class="nx-legal-definition"><div><dt>Conta</dt><dd>E-mail verificado, identificador da conta, nome de usuário, preferências, avatar e informações de perfil fornecidas voluntariamente. As credenciais e sessões de identidade são processadas pelo Clerk; a chave secreta nunca é enviada ao navegador.</dd></div><div><dt>Uso do produto</dt><dd>Listas de animes, notas, progresso, favoritos, títulos seguidos, comentários, tópicos, reações e configurações.</dd></div><div><dt>Dados técnicos</dt><dd>Endereço IP ou identificador derivado, horário, navegador, dispositivo, logs, eventos de segurança, cookies de sessão e registros necessários à prevenção de abuso.</dd></div><div><dt>Formulários</dt><dd>Informações enviadas em contato, denúncias, solicitações de direitos autorais ou pedidos relacionados à privacidade.</dd></div></dl>`)+
      sec('finalidades','03','Para que usamos os dados',p('Podemos utilizar dados para criar e autenticar contas; manter sessões; sincronizar listas; exibir preferências; processar comentários e comunidade; enviar notificações solicitadas; responder suporte e DMCA; detectar abuso e fraude; investigar incidentes; medir desempenho; corrigir falhas; cumprir obrigações legais e exercer direitos em processos administrativos ou judiciais.')+p('Quando houver e-mail transacional, ele será utilizado para finalidades como verificação de conta, recuperação de acesso, alertas solicitados e comunicações importantes sobre segurança ou serviço.'))+
      sec('bases','04','Bases legais',p('Conforme a Lei Geral de Proteção de Dados — LGPD (Lei nº 13.709/2018), o tratamento pode se apoiar, conforme o caso, na execução de contrato ou procedimentos relacionados ao serviço solicitado, cumprimento de obrigação legal ou regulatória, exercício regular de direitos, legítimo interesse com avaliação de necessidade e impacto, proteção contra fraude e, quando exigido, consentimento.')+p('Quando o tratamento depender de consentimento, você poderá retirá-lo nos termos da legislação, sem afetar operações realizadas de forma válida antes da retirada.'))+
      sec('cookies','05','Cookies, armazenamento local e sessões',p('Utilizamos mecanismos de sessão e armazenamento no navegador para manter login, tema, preferências, cache temporário e funcionamento da interface. O Clerk administra a sessão de identidade; a API valida o token e a origem autorizada antes de aceitar qualquer alteração privada.')+p('Dados de lista mantidos anteriormente neste navegador só são importados após confirmação do usuário. A cópia local é preservada até a sincronização ser confirmada. Recursos não essenciais de medição ou personalização, se adicionados no futuro, serão documentados e, quando necessário, dependerão das escolhas do usuário.'))+
      sec('compartilhamento','06','Compartilhamento e operadores',p('Dados podem ser processados por fornecedores de infraestrutura, hospedagem, banco de dados, cache, e-mail, segurança, monitoramento ou outros serviços estritamente necessários à operação. Esses fornecedores recebem apenas o acesso compatível com sua função e ficam sujeitos aos respectivos contratos e obrigações aplicáveis.')+p('Também poderemos compartilhar informações quando exigido por lei, ordem judicial ou autoridade competente, ou quando necessário para proteger direitos, segurança e integridade da plataforma e de seus usuários.'))+
      sec('terceiros','07','Conteúdo e serviços de terceiros',p('O AniNexus utiliza informações e links relacionados a obras e serviços de terceiros. Ao sair do AniNexus ou acessar um serviço externo, passam a valer as políticas do respectivo operador. Não controlamos cookies, coleta ou práticas de privacidade de sites externos.'))+
      sec('transferencia','08','Transferências internacionais',p('Alguns fornecedores de tecnologia poderão processar dados fora do Brasil. Quando isso ocorrer, adotaremos mecanismos compatíveis com a LGPD e medidas contratuais ou técnicas apropriadas para proteger os dados, conforme aplicável.'))+
      sec('retencao','09','Retenção e exclusão',p('Mantemos dados pelo período necessário à finalidade para a qual foram coletados, à manutenção da conta, ao cumprimento de obrigações legais, à prevenção de fraude, à segurança e ao exercício regular de direitos. Prazos podem variar conforme a categoria do dado e o contexto.')+p('Solicitações de exclusão serão atendidas nos limites legais. Certos registros poderão ser preservados quando houver base jurídica para isso, inclusive para segurança, auditoria, defesa de direitos e cumprimento de obrigações.'))+
      sec('seguranca','10','Segurança',p('Adotamos medidas técnicas e organizacionais proporcionais ao risco, incluindo identidade verificada, controles de sessão, limitação de requisições, validação de entradas, políticas de conteúdo, webhooks assinados, registro mínimo de eventos e separação de responsabilidades no backend. Nenhum sistema conectado à internet, entretanto, pode oferecer segurança absoluta.')+p('Se identificarmos incidente que possa gerar risco ou dano relevante, seguiremos as obrigações de avaliação e comunicação previstas na legislação aplicável.'))+
      sec('direitos','11','Seus direitos',p('Nos termos da LGPD, você pode solicitar, quando aplicável: confirmação da existência de tratamento; acesso; correção; anonimização, bloqueio ou eliminação de dados desnecessários ou tratados em desconformidade; portabilidade quando regulamentada; informação sobre compartilhamentos; revogação de consentimento; e revisão das situações previstas em lei.')+p('Para exercer direitos, envie uma solicitação para <a href="mailto:'+CONTACT+'">'+CONTACT+'</a>. Poderemos solicitar informações adicionais para confirmar sua identidade e proteger sua conta.'))+
      sec('menores','12','Crianças e adolescentes',p('O AniNexus não pretende coletar conscientemente dados de crianças em desacordo com a legislação aplicável. Quando o uso por menores exigir consentimento ou acompanhamento de responsável, esses requisitos devem ser observados. Recursos comunitários podem receber controles adicionais de segurança e moderação.'))+
      sec('automatizadas','13','Decisões automatizadas',p('Atualmente o AniNexus pode usar automação para ordenação, recomendações, detecção de abuso, cache e atualização de conteúdo, mas não tem como objetivo adotar decisões exclusivamente automatizadas que produzam efeitos jurídicos relevantes sobre o usuário. Se isso mudar, esta Política será atualizada.'))+
      sec('mudancas','14','Atualizações e contato',p('Podemos atualizar esta Política para acompanhar alterações no produto, infraestrutura ou legislação. A versão vigente e a data da última atualização permanecerão publicadas nesta página. Dúvidas ou solicitações podem ser enviadas para <a href="mailto:'+CONTACT+'">'+CONTACT+'</a>.'));
    const toc=[['controlador','Quem trata os dados'],['dados','Dados coletados'],['finalidades','Finalidades'],['bases','Bases legais'],['cookies','Cookies e sessões'],['compartilhamento','Compartilhamento'],['retencao','Retenção'],['seguranca','Segurança'],['direitos','Seus direitos'],['menores','Menores'],['mudancas','Contato']];
    return shell('/politica-de-privacidade','Política de Privacidade','AniNexus · privacidade e proteção de dados',intro,sections,toc);
  }

  function dmca(){
    const intro=`<p class="nx-legal-intro"><strong>O AniNexus respeita direitos de propriedade intelectual.</strong> Somos uma plataforma informativa de catálogo, descoberta e comunidade sobre animes, mangás e light novels. Não hospedamos, armazenamos nem transmitimos episódios, filmes ou outros conteúdos audiovisuais protegidos.</p><p class="nx-legal-intro">Analisamos notificações relacionadas à Lei de Direitos Autorais brasileira, ao Marco Civil da Internet e, quando aplicável, ao Digital Millennium Copyright Act (DMCA).</p><div class="nx-legal-note"><span></span><div><strong>Identifique o conteúdo com precisão</strong><span>Uma solicitação deve apontar a URL exata dentro do AniNexus, o material questionado e a relação do solicitante com os direitos alegados. Pedidos genéricos podem exigir complementação.</span></div></div>`;
    const form=`<div class="nx-legal-form" id="formulario"><div class="nx-legal-form-head"><h3>Enviar notificação de remoção</h3><p>O formulário abaixo registra a solicitação no backend quando o AniNexus estiver na VPS. No GitHub Pages, ele prepara o mesmo conteúdo para envio por e-mail.</p></div><form id="nxLegalDmca"><div class="nx-legal-fields"><div class="nx-legal-field"><label>Nome completo</label><input name="requesterName" autocomplete="name" minlength="2" maxlength="150" required></div><div class="nx-legal-field"><label>E-mail</label><input name="requesterEmail" type="email" autocomplete="email" maxlength="254" required></div><div class="nx-legal-field full"><label>Titular dos direitos</label><input name="rightsHolder" minlength="2" maxlength="200" required></div><div class="nx-legal-field full"><label>URL exata no AniNexus</label><input name="contentUrl" type="url" maxlength="1200" required></div><div class="nx-legal-field full"><label>Descrição da obra e da alegada violação</label><textarea name="description" minlength="30" maxlength="6000" required></textarea></div><div class="nx-legal-field full"><label>Assinatura eletrônica</label><input name="signature" minlength="2" maxlength="200" placeholder="Digite seu nome completo" required></div><label class="nx-legal-check"><input type="checkbox" name="goodFaith" required><span>Declaro, de boa-fé, que o uso questionado não foi autorizado pelo titular, por seu representante ou pela legislação aplicável.</span></label><label class="nx-legal-check"><input type="checkbox" name="accuracy" required><span>Confirmo que as informações são verdadeiras e que sou titular dos direitos ou estou autorizado a representá-lo.</span></label>${IS_PAGES?'<div class="nx-legal-preview">Prévia do GitHub Pages: o envio para banco depende do backend. Nesta versão, o botão abre seu aplicativo de e-mail com a notificação preenchida.</div>':''}<div class="nx-legal-form-actions"><button class="nx-legal-submit" type="submit">${IS_PAGES?'Preparar e-mail':'Enviar notificação'}</button><a class="nx-legal-mail" href="mailto:${CONTACT}?subject=DMCA%20-%20AniNexus">Enviar diretamente por e-mail</a></div><div class="nx-legal-status" id="nxLegalStatus" role="status" aria-live="polite"></div></div></form></div>`;
    const sections=
      sec('notificacao','01','Notificação de violação',p('Se você é titular de direitos autorais, ou está autorizado a agir em nome dele, e acredita que material exibido no AniNexus viola esses direitos, sua notificação deve conter:')+'<ol><li>identificação da obra protegida;</li><li>URL exata do conteúdo questionado dentro do AniNexus;</li><li>nome completo e e-mail para contato;</li><li>identificação do titular, quando o solicitante for representante;</li><li>declaração de boa-fé sobre a ausência de autorização para o uso questionado;</li><li>declaração de veracidade e autoridade para apresentar o pedido;</li><li>assinatura física ou eletrônica.</li></ol>')+
      sec('envio','02','Como enviar',p('Envie a notificação pelo formulário abaixo ou para <a href="mailto:'+CONTACT+'?subject=DMCA%20-%20AniNexus">'+CONTACT+'</a> com o assunto <strong>DMCA</strong>. Solicitações válidas serão analisadas em prazo razoável e poderão resultar na remoção, ocultação ou desabilitação de acesso ao material indicado.'))+
      sec('contra','03','Contranotificação',p('Se conteúdo relacionado a você tiver sido removido ou restringido e você acreditar que houve erro ou identificação incorreta, poderá enviar uma contranotificação pelo mesmo canal. Identifique o material, explique objetivamente por que considera a medida equivocada e forneça dados de contato suficientes para análise.'))+
      sec('reincidencia','04','Reincidência',p('Contas ou recursos utilizados repetidamente para infringir direitos de propriedade intelectual poderão ser limitados, suspensos ou encerrados, considerando gravidade, histórico, contexto e legislação aplicável.'))+
      sec('processamento','05','Processamento e registros',p('Podemos solicitar documentação complementar para verificar legitimidade, localizar o conteúdo ou prevenir abuso do procedimento. Registros relacionados a notificações, decisões e medidas adotadas podem ser mantidos para auditoria, segurança, cumprimento legal e exercício de direitos.'));
    const english=`<section class="nx-legal-english" id="english"><h2>DMCA — English version</h2>${sec('about-en','A','About AniNexus',p('AniNexus is an informational catalog, discovery platform and community focused on anime, manga and light novels. AniNexus does not host, store or stream copyrighted episodes, movies or other audiovisual works.'))}${sec('notice-en','B','Copyright infringement notice',p('If you are a copyright owner, or authorized to act on behalf of one, please identify the protected work, provide the exact AniNexus URL, your contact information, a good-faith statement, a statement confirming the accuracy of the notice and your authority, and a physical or electronic signature.'))}${sec('submit-en','C','How to submit',p('Use the form on this page or email <a href="mailto:'+CONTACT+'?subject=DMCA%20-%20AniNexus">'+CONTACT+'</a> with the subject “DMCA”. Appropriate action may include removing or disabling access to the identified material.'))}${sec('counter-en','D','Counter-notification and repeat infringement',p('If material connected to you was removed by mistake or misidentification, you may submit a counter-notice through the same channel. Accounts or resources repeatedly used to infringe intellectual property rights may be restricted, suspended or terminated.'))}</section>`;
    const toc=[['notificacao','Notificação'],['envio','Como enviar'],['formulario','Formulário'],['contra','Contranotificação'],['reincidencia','Reincidência'],['processamento','Processamento'],['english','English version']];
    return shell('/dmca','DMCA','AniNexus · direitos autorais',intro,sections,toc,form+english);
  }

  function render(path=route()){
    if(!LEGAL.has(path)){document.body.classList.remove('nx-legal-active');return false}
    document.body.classList.remove('nx-season-active','nx-detail-active','nx-dmca-active');document.body.classList.add('nx-legal-active');
    app.innerHTML=path==='/termos-de-uso'?terms():path==='/politica-de-privacidade'?privacy():dmca();
    document.title=(path==='/termos-de-uso'?'Termos de Serviço':path==='/politica-de-privacidade'?'Política de Privacidade':'DMCA')+' | AniNexus';
    bindDmca(); window.scrollTo({top:0,behavior:'instant'}); return true;
  }
  function mailBody(d){return `DMCA - AniNexus\n\nNome: ${d.requesterName}\nE-mail: ${d.requesterEmail}\nTitular dos direitos: ${d.rightsHolder}\nURL: ${d.contentUrl}\nAssinatura: ${d.signature}\n\nDescrição:\n${d.description}\n\nBoa-fé: SIM\nVeracidade e autorização: SIM`}
  function bindDmca(){const form=document.querySelector('#nxLegalDmca');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const fd=new FormData(form),status=document.querySelector('#nxLegalStatus');const payload={requesterName:String(fd.get('requesterName')||'').trim(),requesterEmail:String(fd.get('requesterEmail')||'').trim(),rightsHolder:String(fd.get('rightsHolder')||'').trim(),contentUrl:String(fd.get('contentUrl')||'').trim(),description:String(fd.get('description')||'').trim(),goodFaith:fd.get('goodFaith')==='on',signature:String(fd.get('signature')||'').trim()};if(fd.get('accuracy')!=='on'||!payload.goodFaith){status.className='nx-legal-status err';status.textContent='Confirme as declarações antes de continuar.';return}const btn=form.querySelector('.nx-legal-submit');btn.disabled=true;status.className='nx-legal-status';status.textContent=IS_PAGES?'Preparando e-mail…':'Enviando…';try{if(IS_PAGES){location.href=`mailto:${CONTACT}?subject=${encodeURIComponent('DMCA - AniNexus')}&body=${encodeURIComponent(mailBody(payload))}`;status.className='nx-legal-status ok';status.textContent='Notificação preparada no seu aplicativo de e-mail.'}else{const r=await fetch('/api/dmca',{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},credentials:'same-origin',body:JSON.stringify(payload)});if(!r.ok)throw new Error(r.status===429?'Muitas tentativas. Aguarde antes de reenviar.':'Não foi possível registrar a notificação.');form.reset();status.className='nx-legal-status ok';status.textContent='Notificação registrada para análise.'}}catch(err){status.className='nx-legal-status err';status.textContent=err?.message||'Falha no envio. Utilize o e-mail informado nesta página.'}finally{btn.disabled=false}})}

  document.addEventListener('click',e=>{const a=e.target.closest('a[data-nx-legal]');if(!a)return;e.preventDefault();e.stopImmediatePropagation();const p=a.dataset.nxLegal;if(!LEGAL.has(p))return;const target=BASE+p;if(!window.AniNexusGo?.(target,{popstate:false}))location.assign(target)},true);
  addEventListener('aninexus:route-changed',()=>queueMicrotask(()=>render(route())));
  setTimeout(()=>render(route()),0);
})();
