'use strict';
(() => {
  if(window.__NX38_LIBRARY__)return;window.__NX38_LIBRARY__=true;
  const app=document.querySelector('#app');if(!app)return;
  const IS_PAGES=location.hostname.endsWith('github.io');
  const REMOTE=window.AniNexusAuth?.enabled===true;
  const BASE=IS_PAGES?'/AniNexus':'';
  const BUILD='44.52.0';
  const API='https://graphql.anilist.co';
  const LIB_ROUTE='/meus-animes';
  const STATE_KEY='aninexus:mediaState:v2';
  const FAV_KEY='aninexus:favorites';
  const DEMO_IMP='aninexus:impressions:v1';
  const STATUS={CURRENT:'Assistindo',PLANNING:'Quero Ver',COMPLETED:'Terminei',PAUSED:'Pausei',DROPPED:'Desisti'};
  const FILTERS=[
    ['AIRING','◫','No ar'],['ALL','▦','Todos'],['FAVORITES','♡','Favoritos'],['CURRENT','▷','Assistindo'],['PLANNING','＋','Quero Ver'],['COMPLETED','✓','Terminei'],['PAUSED','Ⅱ','Pausei'],['DROPPED','×','Desisti'],['IMPRESSIONS','▣','Impressões'],['ACHIEVEMENTS','🏆','Conquistas'],['RANK','♛','Rank']
  ];
  const state={filter:'ALL',search:'',sort:'recent',review:false,data:null,renderToken:0};
  const homeFeed={hideSpoilers:true,token:0};
  const HOME_IMPRESSION_ICON={
    heart:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.5a5.5 5.5 0 0 0 0-7.8Z"/></svg>',
    reply:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4Z"/></svg>',
    star:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.9-5.4 2.9 1-6.1-4.4-4.3 6.1-.9L12 3Z"/></svg>',
    arrow:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg>',
  };
  const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
  const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const slug=s=>String(s||'anime').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,90)||'anime';
  const route=()=>{try{const u=new URL(location.href),p=u.searchParams.get('p');if(p)return p.split('?')[0].replace(/\/+$/,'')||'/';let x=u.pathname;if(IS_PAGES)x=x.replace(/^\/AniNexus/,'')||'/';return x.replace(/\/+$/,'')||'/'}catch{return'/'}};
  const pageUrl=path=>IS_PAGES?`${BASE}/?build=${BUILD}&p=${encodeURIComponent(path)}`:path;
  const go=path=>{if(!IS_PAGES&&window.AniNexusRadio?.navigate?.(path))return;location.assign(pageUrl(path))};
  const fmtRel=v=>{const t=Date.parse(v||'');if(!Number.isFinite(t))return'';const d=Math.max(0,Date.now()-t);if(d<60000)return'agora';if(d<3600000)return`há ${Math.max(1,Math.floor(d/60000))}min`;if(d<86400000)return`há ${Math.floor(d/3600000)}h`;if(d<604800000)return`há ${Math.floor(d/86400000)}d`;return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(t)).replace('.','')};
  const format=f=>({TV:'Série',TV_SHORT:'Série curta',MOVIE:'Filme',OVA:'OVA',ONA:'ONA',SPECIAL:'Especial',MUSIC:'Música'})[f]||f||'Anime';
  const FALLBACK_TITLE='Título temporariamente indisponível';
  const usableTitle=value=>{const title=String(value||'').trim();return title&&!/^(?:anime|mang[áa])\s*\d+$/i.test(title)&&!['undefined','null','nan'].includes(title.toLowerCase())?title:''};

  function mediaOf(raw,id){
    const m=raw&&typeof raw==='object'?raw:{};
    const title=usableTitle(typeof m.title==='string'?m.title:(m.title?.english||m.title?.userPreferred||m.title?.romaji||m.title?.native))||FALLBACK_TITLE;
    const cover=m.cover||m.coverImage?.extraLarge||m.coverImage?.large||'';
    const banner=m.banner||m.bannerImage||cover;
    const internal=m.metricsSource==='aninexus',score=internal&&m.score!=null?Number(m.score):null,mediaId=Number(m.id||id),titleSlug=slug(title),routeSlug=String(m.slug||'').trim()||(titleSlug.endsWith(`-${mediaId}`)?titleSlug:`${titleSlug}-${mediaId}`);
    return {id:mediaId,title,cover,banner,score:Number.isFinite(score)?score:null,metricsSource:internal?'aninexus':'',episodes:m.episodes==null?null:Number(m.episodes),status:String(m.status||''),format:String(m.format||''),seasonYear:m.seasonYear||null,genres:Array.isArray(m.genres)?m.genres:[],slug:routeSlug};
  }
  function normalizeRow(row){const id=Number(row?.media_id||row?.mediaId||row?.media?.id);return{id,status:String(row?.status||''),score:row?.score==null?null:Number(row.score),reaction:row?.reactions?.[0]||row?.reaction||'',reactions:row?.reactions||[],progress:Math.max(0,Number(row?.progress)||0),updatedAt:Date.parse(row?.updated_at||row?.updatedAt||0)||0,media:mediaOf(row?.media,id)}}
  function normalizeFav(row){const id=Number(row?.media_id||row?.mediaId||row?.media?.id);return{id,createdAt:Date.parse(row?.created_at||row?.createdAt||0)||0,media:mediaOf(row?.media,id)}}
  function normalizeImp(row){const id=Number(row?.media_id||row?.mediaId||row?.media?.id);return{id:String(row?.id||crypto?.randomUUID?.()||Date.now()),mediaId:id,mediaType:String(row?.media_type||row?.mediaType||'ANIME').toUpperCase()==='MANGA'?'MANGA':'ANIME',body:String(row?.body||''),segments:Array.isArray(row?.segments)?row.segments:[],spoiler:!!row?.spoiler,hasSpoilers:!!(row?.hasSpoilers||row?.has_spoilers||row?.spoiler),hideSpoilers:row?.hideSpoilers!==false,createdAt:row?.created_at||row?.createdAt||new Date().toISOString(),username:String(row?.user?.username||row?.username||'você'),displayName:String(row?.user?.displayName||row?.display_name||row?.displayName||row?.username||'você'),avatarUrl:row?.user?.avatarUrl||row?.avatar_url||row?.avatarUrl||'',status:String(row?.status_snapshot||row?.statusSnapshot||row?.status||''),stage:String(row?.impression_stage||row?.impressionStage||'PRELIMINARY'),score:(row?.score_snapshot??row?.scoreSnapshot??row?.score)==null?null:Number(row?.score_snapshot??row?.scoreSnapshot??row?.score),reaction:String(row?.reactions?.[0]||row?.reaction||''),progress:Math.max(0,Number(row?.progress_snapshot??row?.progressSnapshot??row?.progress)||0),likesCount:Number(row?.likes_count??row?.likesCount)||0,repliesCount:Number(row?.replies_count??row?.repliesCount)||0,media:mediaOf(row?.media,id)}}

  async function request(path,options={}){
    if(REMOTE){try{return await window.AniNexusAuth.api(path,options)}catch(error){if(error?.status===401)return{__unauth:true};throw error}}
    const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),12000);
    try{const r=await fetch(path,{credentials:'same-origin',cache:'no-store',...options,signal:ctl.signal,headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{}),...(options.headers||{})}});if(r.status===401)return{__unauth:true};if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json().catch(()=>({}))}finally{clearTimeout(timer)}
  }
  async function publicRequest(path){
    if(REMOTE)return window.AniNexusAuth.publicApi(path);
    const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),12000);
    try{const r=await fetch(path,{credentials:'same-origin',cache:'no-store',signal:ctl.signal,headers:{accept:'application/json'}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json().catch(()=>({}))}finally{clearTimeout(timer)}
  }

  async function gqlIds(ids){
    const chunks=[];for(let i=0;i<ids.length;i+=50)chunks.push(ids.slice(i,i+50));const out=[];
    for(const list of chunks){try{const q='query($ids:[Int]){Page(page:1,perPage:50){media(id_in:$ids,type:ANIME){id title{romaji english native userPreferred}coverImage{extraLarge large}bannerImage episodes status format seasonYear genres}}}',r=await fetch(API,{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify({query:q,variables:{ids:list}})});if(!r.ok)continue;const j=await r.json();out.push(...(j?.data?.Page?.media||[]))}catch{}}
    return out.map(x=>mediaOf(x,x.id));
  }
  async function fetchMissing(ids){
    ids=[...new Set(ids.map(Number).filter(Boolean))];if(!ids.length)return[];
    const resolved=[];
    for(let i=0;i<ids.length;i+=60){try{const part=ids.slice(i,i+60),data=await publicRequest(`/api/media/summaries?ids=${encodeURIComponent(part.join(','))}&mediaType=ANIME`);resolved.push(...(data?.items||[]).map(item=>mediaOf(item,item.id)))}catch{}}
    if(resolved.length||!IS_PAGES)return resolved;
    return gqlIds(ids);
  }

  async function hydrateLibrary(data){
    const groups=[data.list||[],data.favorites||[],data.impressions||[]],ids=[...new Set(groups.flat().filter(row=>!usableTitle(row?.media?.title)&&!usableTitle(row?.media?.title?.english)&&!usableTitle(row?.media?.title?.userPreferred)&&!usableTitle(row?.media?.title?.romaji)).map(row=>Number(row?.media_id||row?.mediaId||row?.media?.id)).filter(Boolean))];
    if(!ids.length)return data;
    const media=await fetchMissing(ids),map=new Map(media.map(item=>[Number(item.id),item]));
    const fill=rows=>(rows||[]).map(row=>{const id=Number(row?.media_id||row?.mediaId||row?.media?.id);return map.has(id)?{...row,media:map.get(id)}:row});
    return{...data,list:fill(data.list),favorites:fill(data.favorites),impressions:fill(data.impressions)};
  }

  async function loadLibrary(){
    if(IS_PAGES&&!REMOTE){
      const local={...read('aninexus:mediaState:v1',{}),...read(STATE_KEY,{})},favIds=(read(FAV_KEY,[])||[]).map(Number),ids=[...new Set([...Object.keys(local).map(Number),...favIds])].filter(Boolean),media=await gqlIds(ids),map=new Map(media.map(m=>[m.id,m]));
      const list=Object.entries(local).filter(([,s])=>s?.status).map(([id,s])=>({media_id:Number(id),status:s.status,score:s.score??null,reaction:s.reaction||'',progress:s.progress||0,updated_at:s.updatedAt?new Date(s.updatedAt).toISOString():new Date().toISOString(),media:map.get(Number(id))||null}));
      const favorites=favIds.map(id=>({media_id:id,created_at:new Date().toISOString(),media:map.get(id)||null}));
      const impressions=(read(DEMO_IMP,[])||[]).map(x=>({...x,media:x.media||map.get(Number(x.mediaId||x.media_id))||null}));
      return{user:{username:'Preview'},list:list.map(normalizeRow),favorites:favorites.map(normalizeFav),impressions:impressions.map(normalizeImp),impressionCount:impressions.length};
    }
    try{
      const data=await request('/api/me/library');
      if(data?.__unauth)return{user:null,list:[],favorites:[],impressions:[],impressionCount:0};
      if(data?.list&&data?.favorites){const hydrated=await hydrateLibrary(data);return{user:hydrated.user||{},list:hydrated.list.map(normalizeRow),favorites:hydrated.favorites.map(normalizeFav),impressions:(hydrated.impressions||[]).map(normalizeImp),impressionCount:Number(hydrated.impressionCount||0)}}
    }catch{}
    const me=await request('/api/me').catch(()=>({__unauth:true}));if(me?.__unauth||!me?.user)return{user:null,list:[],favorites:[],impressions:[],impressionCount:0};
    const [ls,fs]=await Promise.all([request('/api/me/list').catch(()=>({items:[]})),request('/api/me/favorites').catch(()=>({items:[]}))]);
    const ids=[...(ls.items||[]).map(x=>Number(x.media_id)),...(fs.items||[]).map(x=>Number(x.media_id))],media=await fetchMissing(ids),map=new Map(media.map(m=>[m.id,m]));
    return{user:me.user,list:(ls.items||[]).map(x=>normalizeRow({...x,media:map.get(Number(x.media_id))||null})),favorites:(fs.items||[]).map(x=>normalizeFav({...x,media:map.get(Number(x.media_id))||null})),impressions:[],impressionCount:0};
  }

  function mergedItems(data){
    const map=new Map();
    for(const x of data.list||[])map.set(x.id,{...x,favorite:false});
    for(const f of data.favorites||[]){const current=map.get(f.id);map.set(f.id,current?{...current,favorite:true,media:current.media?.cover?current.media:f.media}:{id:f.id,status:'',score:null,reaction:'',progress:0,updatedAt:f.createdAt,media:f.media,favorite:true})}
    return [...map.values()];
  }
  function stats(data,items){const list=(data.list||[]),completed=list.filter(x=>x.status==='COMPLETED').length;return{favorites:(data.favorites||[]).length,tracking:list.length,completed:Math.round((completed/Math.max(1,list.length))*100),impressions:Number(data.impressionCount||data.impressions?.length||0)}}
  function filterCount(key,data,items){if(key==='ALL')return items.length;if(key==='FAVORITES')return items.filter(x=>x.favorite).length;if(key==='AIRING')return items.filter(x=>x.media.status==='RELEASING').length;if(STATUS[key])return items.filter(x=>x.status===key).length;if(key==='IMPRESSIONS')return Number(data.impressionCount||data.impressions?.length||0);return''}
  function navMarkup(data,items,drawer=false){return `<div class="nx38-library-nav">${FILTERS.map(([key,icon,label])=>`<button class="nx38-library-filter${state.filter===key?' active':''}" type="button" data-lib-filter="${key}"><i>${icon}</i><span>${label}</span>${filterCount(key,data,items)!==''?`<b>${filterCount(key,data,items)}</b>`:''}</button>`).join('')}</div>`}
  function statusLabel(x){return STATUS[x]||'Sem status'}
  function card(item){const m=item.media||mediaOf(null,item.id),avg=m.score!=null?Number(m.score).toFixed(1).replace('.0',''):'',meta=[format(m.format),m.seasonYear,m.episodes?`${m.episodes} ${Number(m.episodes)===1?'episódio':'episódios'}`:null].filter(Boolean).join(' · ');return `<article class="nx38-library-card" data-lib-open="${item.id}" data-title="${esc(m.title)}"><div class="nx38-library-poster">${m.cover?`<img src="${esc(m.cover)}" alt="${esc(m.title)}" loading="lazy" decoding="async">`:''}<div class="nx38-library-shade"></div>${item.progress?`<span class="nx38-library-progress">${item.progress}${m.episodes?`/${m.episodes}`:''}</span>`:''}${avg?`<span class="nx38-library-score">★ ${avg}</span>`:''}<button class="nx38-library-impression-btn" type="button" data-lib-impression="${item.id}" aria-label="Escrever impressão">✎</button><div class="nx38-library-card-actions"><button type="button" data-list="${item.id}" class="${item.status?'active':''}" aria-label="Alterar status">＋</button><button type="button" data-fav="${item.id}" class="${item.favorite?'active':''}" aria-label="Favoritar">♡</button></div></div><h3>${esc(m.title)}</h3><div class="nx38-library-card-meta"><span class="status">${esc(statusLabel(item.status))}</span>${meta?`<span>${esc(meta)}</span>`:''}${item.score!=null?`<span>· sua nota ${Number(item.score).toFixed(1).replace('.0','')}</span>`:''}</div></article>`}
  function filtered(data,items){
    let out=items.slice();if(state.review)out=out.filter(x=>x.status).sort((a,b)=>(a.updatedAt||0)-(b.updatedAt||0));
    else if(state.filter==='FAVORITES')out=out.filter(x=>x.favorite);else if(state.filter==='AIRING')out=out.filter(x=>x.media.status==='RELEASING');else if(STATUS[state.filter])out=out.filter(x=>x.status===state.filter);
    const q=state.search.trim().toLowerCase();if(q)out=out.filter(x=>`${x.media.title} ${(x.media.genres||[]).join(' ')}`.toLowerCase().includes(q));
    if(state.sort==='title')out.sort((a,b)=>a.media.title.localeCompare(b.media.title,'pt-BR'));else if(state.sort==='score')out.sort((a,b)=>(b.score??b.media.score??-1)-(a.score??a.media.score??-1));else if(state.sort==='progress')out.sort((a,b)=>(b.progress||0)-(a.progress||0));else out.sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));return out;
  }
  function impressionsView(data){const items=(data.impressions||[]);if(!items.length)return empty('Nenhuma impressão ainda','Quando você escrever uma impressão sobre um anime, ela aparece aqui e pode alimentar a área de comunidade da Home.');return `<div class="nx38-library-impressions-list">${items.map(x=>`<article class="nx38-own-impression">${x.media.cover?`<img src="${esc(x.media.cover)}" alt="">`:'<div></div>'}<div><header><h3>${esc(x.media.title)}</h3><time>${esc(fmtRel(x.createdAt))}</time></header><p>${x.hasSpoilers?'<span class="spoiler">Contém spoiler</span> ':''}${impressionSegments(x).map(segment=>esc(segment.content)).join('')}</p><footer>${x.status?esc(statusLabel(x.status)):''}${x.progress?` · episódio ${x.progress}`:''}${x.score!=null?` · ★ ${Number(x.score).toFixed(1).replace('.0','')}`:''}</footer></div></article>`).join('')}</div>`}
  function achievementsView(){return `<div class="nx38-library-empty"><strong>Suas conquistas ganharam um espaço próprio</strong><p>Veja os 40 marcos, seu progresso, medalhas fixadas e títulos disponíveis.</p><a class="nx38-library-primary" href="${pageUrl('/conquistas')}">Abrir conquistas</a></div>`}
  function rankView(items){const ranked=items.filter(x=>x.score!=null).sort((a,b)=>b.score-a.score);if(!ranked.length)return empty('Seu rank ainda está vazio','Dê notas aos animes concluídos ou em andamento para criar seu ranking pessoal.');return `<div class="nx38-rank-list">${ranked.map((x,i)=>`<article class="nx38-rank-row" data-lib-open="${x.id}" data-title="${esc(x.media.title)}"><b>${i+1}</b>${x.media.cover?`<img src="${esc(x.media.cover)}" alt="">`:'<div></div>'}<strong>${esc(x.media.title)}</strong><span>★ ${Number(x.score).toFixed(1).replace('.0','')}</span></article>`).join('')}</div>`}
  function empty(title,copy){return `<div class="nx38-library-empty"><strong>${esc(title)}</strong><p>${esc(copy)}</p><a class="nx38-library-primary" href="${pageUrl('/animes/catalogo')}">Explorar catálogo</a></div>`}

  function shell(data){
    const items=mergedItems(data),s=stats(data,items),user=data.user||{};
    document.title='Meus Animes | AniNexus';document.body.classList.add('nx38-library-active');document.body.classList.remove('nx35-home-active');
    app.innerHTML=`<main class="nx38-library"><div class="nx38-library-shell"><header class="nx38-library-head"><div><small>SUA BIBLIOTECA</small><h1>Meus Animes</h1><p>Organize o que quer ver, o que está acompanhando, o que terminou e as impressões que deixou pelo caminho.</p></div><div class="nx38-library-head-actions"><a class="nx38-library-ghost" href="${pageUrl('/minha-conta')}">Minha conta</a><button class="nx38-library-share" type="button" data-lib-share>Compartilhar</button></div></header><div class="nx38-library-stats"><div class="nx38-library-stat"><strong>${s.favorites}</strong><span>Favoritos</span></div><div class="nx38-library-stat"><strong>${s.tracking}</strong><span>Acompanhando</span></div><div class="nx38-library-stat"><strong>${s.completed}%</strong><span>Concluídos</span></div><div class="nx38-library-stat"><strong>${s.impressions}</strong><span>Impressões</span></div></div><button class="nx38-library-review${state.review?' active':''}" type="button" data-lib-review>${state.review?'Sair da revisão':'Revisar meus animes'}</button><div class="nx38-library-layout"><aside class="nx38-library-side"><h3>Biblioteca</h3>${navMarkup(data,items)}</aside><section class="nx38-library-main"><div class="nx38-library-quick">${['ALL','FAVORITES','CURRENT','PLANNING'].map(k=>{const f=FILTERS.find(x=>x[0]===k);return `<button type="button" data-lib-filter="${k}" class="${state.filter===k?'active':''}">${f[2]}</button>`}).join('')}</div><div class="nx38-library-toolbar"><button class="nx38-library-menu-button" type="button" data-lib-menu aria-label="Abrir filtros">☰</button><input class="nx38-library-search" type="search" placeholder="Buscar nos meus animes…" value="${esc(state.search)}" data-lib-search><select class="nx38-library-sort" data-lib-sort><option value="recent"${state.sort==='recent'?' selected':''}>Recentes</option><option value="title"${state.sort==='title'?' selected':''}>Título</option><option value="score"${state.sort==='score'?' selected':''}>Nota</option><option value="progress"${state.sort==='progress'?' selected':''}>Progresso</option></select></div>${state.review?'<div class="nx38-library-review-note"><strong>Modo revisão:</strong> os animes com status aparecem do mais antigo para o mais recente. Abra o botão de status em cada card para atualizar progresso, nota ou categoria.</div>':''}<div id="nx38LibraryContent"></div></section></div></div></main><div class="nx38-library-drawer" id="nx38LibraryDrawer" hidden><button class="nx38-drawer-backdrop" type="button" data-lib-drawer-close aria-label="Fechar"></button><div class="nx38-library-drawer-panel"><div class="nx38-library-drawer-head"><strong>Menu</strong><button type="button" data-lib-drawer-close>×</button></div>${navMarkup(data,items,true)}</div></div><div class="nx38-impression-modal" id="nx38ImpressionModal" hidden></div>`;
    paintContent();wire();window.AniNexusMediaState?.sync?.();document.documentElement.classList.remove('nx38-library-boot');
  }
  function paintContent(){if(!state.data)return;const root=document.querySelector('#nx38LibraryContent');if(!root)return;const items=mergedItems(state.data);if(state.filter==='IMPRESSIONS'){root.innerHTML=impressionsView(state.data);return}if(state.filter==='ACHIEVEMENTS'){root.innerHTML=achievementsView(state.data);return}if(state.filter==='RANK'){root.innerHTML=rankView(items);wireOpen();return}const out=filtered(state.data,items);root.innerHTML=out.length?`<div class="nx38-library-grid">${out.map(card).join('')}</div>`:empty(state.search?'Nenhum resultado':'Nada nesta categoria',state.search?'Tente outro termo ou limpe os filtros.':'Quando você adicionar um anime aqui, ele aparece automaticamente nesta seção.');window.AniNexusMediaState?.sync?.();wireOpen();wireImpressions()}
  function wireOpen(){document.querySelectorAll('[data-lib-open]').forEach(el=>{el.onclick=e=>{if(e.target.closest('button,a,input,select,textarea'))return;go(`/anime/${slug(el.dataset.title||'anime')}-${el.dataset.libOpen}`)}})}
  function wireImpressions(){document.querySelectorAll('[data-lib-impression]').forEach(b=>b.onclick=e=>{e.stopPropagation();openImpression(Number(b.dataset.libImpression))})}
  function setFilter(k){if(k==='ACHIEVEMENTS'){go('/conquistas');return}state.filter=k;state.review=false;document.querySelector('#nx38LibraryDrawer')?.setAttribute('hidden','');shell(state.data)}
  function wire(){
    document.querySelectorAll('[data-lib-filter]').forEach(b=>b.onclick=()=>setFilter(b.dataset.libFilter));
    document.querySelector('[data-lib-search]')?.addEventListener('input',e=>{state.search=e.target.value;paintContent()});
    document.querySelector('[data-lib-sort]')?.addEventListener('change',e=>{state.sort=e.target.value;paintContent()});
    document.querySelector('[data-lib-review]')?.addEventListener('click',()=>{state.review=!state.review;state.filter='ALL';shell(state.data)});
    document.querySelector('[data-lib-menu]')?.addEventListener('click',()=>{const d=document.querySelector('#nx38LibraryDrawer');if(d)d.hidden=false});
    document.querySelectorAll('[data-lib-drawer-close]').forEach(b=>b.onclick=()=>{const d=document.querySelector('#nx38LibraryDrawer');if(d)d.hidden=true});
    document.querySelector('[data-lib-share]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(location.href);toast('Link copiado')}catch{toast('Não foi possível copiar')}});
  }
  function toast(text){const root=document.querySelector('#toastRoot');if(root){const d=document.createElement('div');d.className='toast';d.textContent=text;root.append(d);setTimeout(()=>d.remove(),2500)}}

  function openImpression(id){
    const item=mergedItems(state.data).find(x=>x.id===id);if(!item)return;const modal=document.querySelector('#nx38ImpressionModal');if(!modal)return;
    modal.hidden=false;modal.innerHTML=`<button class="nx38-impression-backdrop" type="button" data-imp-close aria-label="Fechar"></button><div class="nx38-impression-card-modal"><header><div><h2>Nova impressão</h2><div class="anime">${esc(item.media.title)}</div></div><button type="button" data-imp-close>×</button></header><form id="nx38ImpressionForm"><textarea name="body" maxlength="1200" required placeholder="O que você está achando? Uma impressão curta, sem precisar escrever uma resenha inteira."></textarea><div class="nx38-impression-meta"><button type="button" data-imp-mark-spoiler>◉ Marcar trecho como spoiler</button><label>Momento <select name="stage"><option value="PRELIMINARY">Preliminar</option><option value="FINAL" ${item.status==='COMPLETED'?'selected':''}>Final</option></select></label><span data-imp-count>0/1200</span></div><div class="nx38-impression-error" data-imp-error></div><div class="nx38-impression-actions"><button class="nx38-impression-cancel" type="button" data-imp-close>Cancelar</button><button class="nx38-impression-submit" type="submit">Publicar impressão</button></div></form></div>`;
    const close=()=>{modal.hidden=true;modal.innerHTML=''};modal.querySelectorAll('[data-imp-close]').forEach(b=>b.onclick=close);const ta=modal.querySelector('textarea'),count=modal.querySelector('[data-imp-count]');ta?.addEventListener('input',()=>count.textContent=`${ta.value.length}/1200`);modal.querySelector('[data-imp-mark-spoiler]').onclick=()=>{const start=ta.selectionStart,end=ta.selectionEnd;if(start===end){toast('Selecione o trecho que contém spoiler.');return}const value=ta.value,wrapped=start>=2&&value.slice(start-2,start)==='||'&&value.slice(end,end+2)==='||';ta.value=wrapped?value.slice(0,start-2)+value.slice(start,end)+value.slice(end+2):value.slice(0,start)+'||'+value.slice(start,end)+'||'+value.slice(end);ta.setSelectionRange(wrapped?start-2:start+2,wrapped?end-2:end+2);ta.dispatchEvent(new Event('input'));ta.focus()};ta?.focus();
    modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const body=ta.value.trim(),stage=e.currentTarget.elements.stage.value,hasSpoilers=/\|\|[^|]+\|\|/.test(body),err=modal.querySelector('[data-imp-error]'),submit=modal.querySelector('.nx38-impression-submit');if(!body){err.textContent='Escreva alguma coisa antes de publicar.';return}submit.disabled=true;submit.textContent='Publicando…';try{let row;if(IS_PAGES&&!REMOTE){row={id:`local-${Date.now()}`,mediaId:id,body,hasSpoilers,stage,createdAt:new Date().toISOString(),username:'você',status:item.status,score:item.score,progress:item.progress,media:item.media};const all=read(DEMO_IMP,[]);all.unshift(row);write(DEMO_IMP,all.slice(0,100))}else{await request(`/api/anime/${id}/impressions`,{method:'POST',body:JSON.stringify({text:body,impressionStage:stage})});row={id:`new-${Date.now()}`,mediaId:id,body,hasSpoilers,stage,createdAt:new Date().toISOString(),username:state.data.user?.username||'você',status:item.status,score:item.score,progress:item.progress,media:item.media}}
      state.data.impressions=[normalizeImp(row),...(state.data.impressions||[])];state.data.impressionCount=Number(state.data.impressionCount||0)+1;close();toast('Impressão publicada');shell(state.data);if(route()==='/')mountHomeImpressions(true)}catch(ex){err.textContent='Não foi possível publicar agora. Tente novamente.';submit.disabled=false;submit.textContent='Publicar impressão'}};
  }

  function loginRequired(){document.body.classList.add('nx38-library-active');app.innerHTML=`<main class="nx38-library"><div class="nx38-library-shell"><section class="nx38-library-login"><img src="${BASE}/assets/logo.png" alt=""><h1>Seus animes ficam aqui.</h1><p>Entre para sincronizar favoritos, progresso, notas e impressões em todos os seus dispositivos.</p><div class="nx38-library-login-actions"><a class="nx38-library-primary" href="${pageUrl('/login')}">Entrar</a><a class="nx38-library-ghost" href="${pageUrl('/criar-conta')}">Criar conta</a></div></section></div></main>`;document.documentElement.classList.remove('nx38-library-boot')}
  async function mountLibrary(){if(window.__ANINEXUS_UNIFIED_LIBRARY__||route()!==LIB_ROUTE)return;const token=++state.renderToken;document.documentElement.classList.add('nx38-library-boot');const data=await loadLibrary();if(token!==state.renderToken||route()!==LIB_ROUTE)return;state.data=data;if((REMOTE||!IS_PAGES)&&!data.user){loginRequired();return}shell(data)}

  async function loadPublicImpressions(){
    if(IS_PAGES&&!REMOTE)return(read(DEMO_IMP,[])||[]).slice(0,10).map(normalizeImp);
    try{const d=await publicRequest('/api/feed/impressions?limit=12&filter=all&sort=recent&hideSpoilers=true');return(d?.items||[]).map(normalizeImp)}catch{return[]}
  }
  function impressionSegments(x){if(x.segments.length)return x.segments;const body=String(x.body||''),segments=[];let cursor=0;for(const match of body.matchAll(/\|\|([^|]+?)\|\|/g)){if(match.index>cursor)segments.push({type:'text',content:body.slice(cursor,match.index)});segments.push({type:'spoiler',content:match[1]});cursor=match.index+match[0].length}if(cursor<body.length)segments.push({type:'text',content:body.slice(cursor)});if(segments.length)return segments;return[{type:x.spoiler?'spoiler':'text',content:body}]}
  function impressionBody(x){return impressionSegments(x).map(segment=>segment.type==='spoiler'&&homeFeed.hideSpoilers?`<span class="nx38-partial-spoiler" data-home-imp-spoiler role="button" tabindex="0" aria-label="Revelar trecho com spoiler"><span>${esc(segment.content)}</span></span>`:`<span>${esc(segment.content)}</span>`).join('')}
  function homeImpCard(x){
    const username=x.username||'membro',displayName=x.displayName||username,m=x.media||mediaOf(null,x.mediaId),type=x.mediaType==='MANGA'?'MANGA':'ANIME',status=x.status?(type==='MANGA'?{CURRENT:'Lendo',PLANNING:'Quero ler',COMPLETED:'Terminei',PAUSED:'Pausei',DROPPED:'Desisti'}[x.status]:STATUS[x.status]):null,score=x.score!=null&&Number.isFinite(Number(x.score))?Number(x.score).toFixed(1).replace('.0',''):null,kind=type==='MANGA'?'Mangá':format(m.format),baseSlug=String(m.slug||slug(m.title)).replace(new RegExp(`-${m.id}$`),'')||slug(m.title),mediaPath=`/${type==='MANGA'?'manga':'anime'}/${baseSlug}-${m.id}`,profilePath=username&&!['membro','você'].includes(username.toLowerCase())?`/u/${username}`:'',details=[kind,m.seasonYear,m.episodes?`${m.episodes} ep.`:null].filter(Boolean).join(' · '),tone=['CURRENT','PLANNING','COMPLETED','PAUSED','DROPPED'].includes(x.status)?x.status.toLowerCase():'neutral',reaction={LIKE:'Gostei',DISLIKE:'Não curti',LOVE:'Amei',WOW:'Me surpreendeu'}[x.reaction]||x.reaction,date=Date.parse(x.createdAt),dateTitle=Number.isFinite(date)?new Intl.DateTimeFormat('pt-BR',{dateStyle:'long',timeStyle:'short'}).format(new Date(date)):'';
    const avatar=`<span class="nx38-impression-avatar">${x.avatarUrl?`<img src="${esc(x.avatarUrl)}" alt="" loading="lazy" decoding="async">`:esc(displayName.charAt(0).toUpperCase())}</span>`;
    const identity=`${avatar}<span class="nx38-impression-identity"><strong>${esc(displayName)}</strong><small>@${esc(username)}</small></span>`;
    const author=profilePath?`<a class="nx38-impression-author" href="${pageUrl(profilePath)}" data-nx38-nav="${esc(profilePath)}" aria-label="Ver perfil de ${esc(displayName)}">${identity}</a>`:`<span class="nx38-impression-author">${identity}</span>`;
    return `<article class="nx38-impression-home-card status-${tone}">${m.banner||m.cover?`<img class="nx38-impression-art" src="${esc(m.banner||m.cover)}" alt="" loading="lazy" decoding="async" aria-hidden="true">`:''}<header class="nx38-impression-user">${author}<time datetime="${esc(x.createdAt)}" title="${esc(dateTitle)}">${esc(fmtRel(x.createdAt))}</time></header><p class="nx38-impression-body">${impressionBody(x)}</p><div class="nx38-impression-meta-row" aria-label="Contexto da impressão">${status?`<span class="status">${esc(status)}</span>`:''}<span class="stage">${x.stage==='FINAL'?'Final':'Preliminar'}</span>${x.progress?`<span class="progress">${type==='MANGA'?'capítulo':'episódio'} ${x.progress}${type==='ANIME'&&m.episodes?` de ${m.episodes}`:''}</span>`:''}${score?`<span class="nx38-impression-score" aria-label="Nota ${score}">${HOME_IMPRESSION_ICON.star}<b>${score}</b></span>`:''}<span class="nx38-impression-metric" aria-label="${x.likesCount} curtidas">${HOME_IMPRESSION_ICON.heart}<b>${x.likesCount}</b></span><span class="nx38-impression-metric" aria-label="${x.repliesCount} respostas">${HOME_IMPRESSION_ICON.reply}<b>${x.repliesCount}</b></span>${!x.hasSpoilers?'<span class="spoiler-free">sem spoilers</span>':''}</div><a class="nx38-impression-context" href="${pageUrl(mediaPath)}" data-nx38-nav="${esc(mediaPath)}">${m.cover?`<img src="${esc(m.cover)}" alt="Capa de ${esc(m.title)}" loading="lazy" decoding="async">`:`<span class="nx38-impression-cover-fallback">AN</span>`}<span class="nx38-impression-media-copy"><small>${esc(details||kind)}</small><strong>${esc(m.title)}</strong><em>Ver obra e outras impressões</em></span><i aria-hidden="true">${HOME_IMPRESSION_ICON.arrow}</i></a></article>`
  }
  async function mountHomeImpressions(force=false){
    if(route()!=='/')return;const home=document.querySelector('.nx35-home');if(!home)return;if(!force&&document.querySelector('#nx38HomeImpressions'))return;document.querySelector('#nx38HomeImpressions')?.remove();
    const token=++homeFeed.token,news=document.querySelector('#nx35News')?.closest('.nx35-section'),host=document.createElement('section');host.id='nx38HomeImpressions';host.className='nx38-impressions-home tonal';host.innerHTML=`<div class="nx35-shell"><div class="nx38-impressions-head"><div><span class="nx38-impressions-kicker">COMUNIDADE</span><h2>Últimas <em>Impressões</em></h2><p>Opiniões de quem está assistindo, com episódio, progresso e nota no mesmo contexto.</p></div><div class="nx38-impressions-actions"><button type="button" data-imp-prev aria-label="Impressão anterior">‹</button><button type="button" data-imp-next aria-label="Próxima impressão">›</button><a href="${pageUrl('/comunidade')}">Abrir comunidade</a></div></div><div class="nx38-impressions-empty">Carregando impressões…</div></div>`;if(news)news.insertAdjacentElement('afterend',host);else home.append(host);
    const items=await loadPublicImpressions(),body=host.querySelector('.nx38-impressions-empty');if(token!==homeFeed.token||!document.body.contains(host))return;host.dataset.count=String(items.length);if(items.length){body.outerHTML=`<div class="nx38-impressions-rail" data-count="${items.length}" tabindex="0" aria-label="Últimas impressões da comunidade">${items.map(homeImpCard).join('')}</div>`;const rail=host.querySelector('.nx38-impressions-rail'),prev=host.querySelector('[data-imp-prev]'),next=host.querySelector('[data-imp-next]'),update=()=>{const max=Math.max(0,rail.scrollWidth-rail.clientWidth);prev.disabled=rail.scrollLeft<8;next.disabled=rail.scrollLeft>max-8};prev.onclick=()=>rail.scrollBy({left:-Math.max(280,rail.clientWidth*.8),behavior:'smooth'});next.onclick=()=>rail.scrollBy({left:Math.max(280,rail.clientWidth*.8),behavior:'smooth'});rail.addEventListener('scroll',update,{passive:true});requestAnimationFrame(update)}else{body.innerHTML='Ainda não há impressões públicas neste filtro.';host.querySelectorAll('[data-imp-prev],[data-imp-next]').forEach(button=>button.disabled=true)}
    host.querySelectorAll('[data-home-imp-spoiler]').forEach(spoiler=>{const toggle=()=>{spoiler.classList.toggle('revealed');spoiler.setAttribute('aria-label',spoiler.classList.contains('revealed')?'Ocultar trecho com spoiler':'Revelar trecho com spoiler')};spoiler.addEventListener('click',toggle);spoiler.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle()}})});
    host.querySelectorAll('[data-nx38-nav]').forEach(link=>link.addEventListener('click',event=>{if(event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;event.preventDefault();go(link.dataset.nx38Nav)}));
  }

  document.addEventListener('aninexus:media-state-changed',e=>{if(route()!==LIB_ROUTE||!state.data)return;const id=Number(e.detail?.id),s=e.detail?.state||{},row=state.data.list.find(x=>x.id===id);if(!s.status)state.data.list=state.data.list.filter(x=>x.id!==id);else if(row)Object.assign(row,{status:s.status,score:s.score??null,reaction:s.reaction||'',progress:Number(s.progress)||0,updatedAt:Date.now()});else{const fav=state.data.favorites.find(x=>x.id===id);state.data.list.unshift({id,status:s.status,score:s.score??null,reaction:s.reaction||'',progress:Number(s.progress)||0,updatedAt:Date.now(),media:fav?.media||mediaOf(null,id)})}paintContent()});
  document.addEventListener('aninexus:favorite-changed',e=>{if(route()!==LIB_ROUTE||!state.data)return;const id=Number(e.detail?.id),on=!!e.detail?.favorite,f=state.data.favorites.find(x=>x.id===id);if(on&&!f){const row=state.data.list.find(x=>x.id===id);state.data.favorites.unshift({id,createdAt:Date.now(),media:row?.media||mediaOf(null,id)})}if(!on&&f)state.data.favorites=state.data.favorites.filter(x=>x.id!==id);paintContent()});
  addEventListener('aninexus:home-v34-ready',()=>mountHomeImpressions());
  addEventListener('popstate',()=>{if(route()===LIB_ROUTE)mountLibrary();else{document.body.classList.remove('nx38-library-active');if(route()==='/')setTimeout(()=>mountHomeImpressions(),30)}});
  new MutationObserver(()=>{if(route()==='/'&&document.querySelector('.nx35-home')&&!document.querySelector('#nx38HomeImpressions'))mountHomeImpressions()}).observe(app,{childList:true,subtree:true});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{mountLibrary();setTimeout(()=>mountHomeImpressions(),80)},{once:true});else{mountLibrary();setTimeout(()=>mountHomeImpressions(),80)}
})();
